// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.28.3
// source: horus/pb/detection_service/detection.proto

package detection_pb

import (
	metadata_pb "github.com/seoulrobotics/horus-sdk/go/proto/config/metadata_pb"
	point_message_pb "github.com/seoulrobotics/horus-sdk/go/proto/point/point_message_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The supported object labels.
type ObjectLabel int32

const (
	ObjectLabel_LABEL_UNSPECIFIED ObjectLabel = 0
	ObjectLabel_MISC              ObjectLabel = 1
	ObjectLabel_CAR               ObjectLabel = 2
	ObjectLabel_CYCLIST           ObjectLabel = 3
	ObjectLabel_PEDESTRIAN        ObjectLabel = 4
)

// Enum value maps for ObjectLabel.
var (
	ObjectLabel_name = map[int32]string{
		0: "LABEL_UNSPECIFIED",
		1: "MISC",
		2: "CAR",
		3: "CYCLIST",
		4: "PEDESTRIAN",
	}
	ObjectLabel_value = map[string]int32{
		"LABEL_UNSPECIFIED": 0,
		"MISC":              1,
		"CAR":               2,
		"CYCLIST":           3,
		"PEDESTRIAN":        4,
	}
)

func (x ObjectLabel) Enum() *ObjectLabel {
	p := new(ObjectLabel)
	*p = x
	return p
}

func (x ObjectLabel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectLabel) Descriptor() protoreflect.EnumDescriptor {
	return file_horus_pb_detection_service_detection_proto_enumTypes[0].Descriptor()
}

func (ObjectLabel) Type() protoreflect.EnumType {
	return &file_horus_pb_detection_service_detection_proto_enumTypes[0]
}

func (x ObjectLabel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// The detected object tracking status.
type TrackingStatus int32

const (
	TrackingStatus_TRACKING_STATUS_UNSPECIFIED TrackingStatus = 0
	TrackingStatus_INVALIDATING                TrackingStatus = 1
	TrackingStatus_VALIDATING                  TrackingStatus = 2
	TrackingStatus_DRIFTING                    TrackingStatus = 3
	TrackingStatus_TRACKING                    TrackingStatus = 4
)

// Enum value maps for TrackingStatus.
var (
	TrackingStatus_name = map[int32]string{
		0: "TRACKING_STATUS_UNSPECIFIED",
		1: "INVALIDATING",
		2: "VALIDATING",
		3: "DRIFTING",
		4: "TRACKING",
	}
	TrackingStatus_value = map[string]int32{
		"TRACKING_STATUS_UNSPECIFIED": 0,
		"INVALIDATING":                1,
		"VALIDATING":                  2,
		"DRIFTING":                    3,
		"TRACKING":                    4,
	}
)

func (x TrackingStatus) Enum() *TrackingStatus {
	p := new(TrackingStatus)
	*p = x
	return p
}

func (x TrackingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrackingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_horus_pb_detection_service_detection_proto_enumTypes[1].Descriptor()
}

func (TrackingStatus) Type() protoreflect.EnumType {
	return &file_horus_pb_detection_service_detection_proto_enumTypes[1]
}

func (x TrackingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// A bounding box message.
type BoundingBox struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Base *metadata_pb.Vector3F  `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	xxx_hidden_Size *metadata_pb.Vector3F  `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	xxx_hidden_Yaw  float32                `protobuf:"fixed32,3,opt,name=yaw,proto3" json:"yaw,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BoundingBox) GetBase() *metadata_pb.Vector3F {
	if x != nil {
		return x.xxx_hidden_Base
	}
	return nil
}

func (x *BoundingBox) GetSize() *metadata_pb.Vector3F {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return nil
}

func (x *BoundingBox) GetYaw() float32 {
	if x != nil {
		return x.xxx_hidden_Yaw
	}
	return 0
}

func (x *BoundingBox) SetBase(v *metadata_pb.Vector3F) {
	x.xxx_hidden_Base = v
}

func (x *BoundingBox) SetSize(v *metadata_pb.Vector3F) {
	x.xxx_hidden_Size = v
}

func (x *BoundingBox) SetYaw(v float32) {
	x.xxx_hidden_Yaw = v
}

func (x *BoundingBox) HasBase() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Base != nil
}

func (x *BoundingBox) HasSize() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Size != nil
}

func (x *BoundingBox) ClearBase() {
	x.xxx_hidden_Base = nil
}

func (x *BoundingBox) ClearSize() {
	x.xxx_hidden_Size = nil
}

type BoundingBox_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The base is defined by the center_x, center_y, and lowest_z in meters
	// relevant to the global origin.
	Base *metadata_pb.Vector3F
	// The size is defined by the width, height and depth of the box in meters.
	Size *metadata_pb.Vector3F
	// The yaw of the box in radians.
	Yaw float32
}

func (b0 BoundingBox_builder) Build() *BoundingBox {
	m0 := &BoundingBox{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Base = b.Base
	x.xxx_hidden_Size = b.Size
	x.xxx_hidden_Yaw = b.Yaw
	return m0
}

// A labeled point cloud message.
type LabeledPointCloud struct {
	state                           protoimpl.MessageState       `protogen:"opaque.v1"`
	xxx_hidden_PointCloud           *point_message_pb.PointFrame `protobuf:"bytes,1,opt,name=point_cloud,json=pointCloud,proto3" json:"point_cloud,omitempty"`
	xxx_hidden_PointIndexToObjectId *metadata_pb.UInt32List      `protobuf:"bytes,2,opt,name=point_index_to_object_id,json=pointIndexToObjectId,proto3" json:"point_index_to_object_id,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *LabeledPointCloud) Reset() {
	*x = LabeledPointCloud{}
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabeledPointCloud) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabeledPointCloud) ProtoMessage() {}

func (x *LabeledPointCloud) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LabeledPointCloud) GetPointCloud() *point_message_pb.PointFrame {
	if x != nil {
		return x.xxx_hidden_PointCloud
	}
	return nil
}

func (x *LabeledPointCloud) GetPointIndexToObjectId() *metadata_pb.UInt32List {
	if x != nil {
		return x.xxx_hidden_PointIndexToObjectId
	}
	return nil
}

func (x *LabeledPointCloud) SetPointCloud(v *point_message_pb.PointFrame) {
	x.xxx_hidden_PointCloud = v
}

func (x *LabeledPointCloud) SetPointIndexToObjectId(v *metadata_pb.UInt32List) {
	x.xxx_hidden_PointIndexToObjectId = v
}

func (x *LabeledPointCloud) HasPointCloud() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PointCloud != nil
}

func (x *LabeledPointCloud) HasPointIndexToObjectId() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PointIndexToObjectId != nil
}

func (x *LabeledPointCloud) ClearPointCloud() {
	x.xxx_hidden_PointCloud = nil
}

func (x *LabeledPointCloud) ClearPointIndexToObjectId() {
	x.xxx_hidden_PointIndexToObjectId = nil
}

type LabeledPointCloud_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The point cloud and its metadata.
	PointCloud *point_message_pb.PointFrame
	// Attributes for each point defining which `DetectedObject` a point belongs
	// to. The int32_t::max is reserved for unassigned points.
	PointIndexToObjectId *metadata_pb.UInt32List
}

func (b0 LabeledPointCloud_builder) Build() *LabeledPointCloud {
	m0 := &LabeledPointCloud{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PointCloud = b.PointCloud
	x.xxx_hidden_PointIndexToObjectId = b.PointIndexToObjectId
	return m0
}

// A singular detection object message.
type DetectedObject struct {
	state                     protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Classification *DetectedObject_Classification `protobuf:"bytes,1,opt,name=classification,proto3" json:"classification,omitempty"`
	xxx_hidden_Kinematics     *DetectedObject_Kinematics     `protobuf:"bytes,2,opt,name=kinematics,proto3" json:"kinematics,omitempty"`
	xxx_hidden_Shape          *DetectedObject_Shape          `protobuf:"bytes,3,opt,name=shape,proto3" json:"shape,omitempty"`
	xxx_hidden_Status         *DetectedObject_Status         `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DetectedObject) Reset() {
	*x = DetectedObject{}
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectedObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectedObject) ProtoMessage() {}

func (x *DetectedObject) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DetectedObject) GetClassification() *DetectedObject_Classification {
	if x != nil {
		return x.xxx_hidden_Classification
	}
	return nil
}

func (x *DetectedObject) GetKinematics() *DetectedObject_Kinematics {
	if x != nil {
		return x.xxx_hidden_Kinematics
	}
	return nil
}

func (x *DetectedObject) GetShape() *DetectedObject_Shape {
	if x != nil {
		return x.xxx_hidden_Shape
	}
	return nil
}

func (x *DetectedObject) GetStatus() *DetectedObject_Status {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *DetectedObject) SetClassification(v *DetectedObject_Classification) {
	x.xxx_hidden_Classification = v
}

func (x *DetectedObject) SetKinematics(v *DetectedObject_Kinematics) {
	x.xxx_hidden_Kinematics = v
}

func (x *DetectedObject) SetShape(v *DetectedObject_Shape) {
	x.xxx_hidden_Shape = v
}

func (x *DetectedObject) SetStatus(v *DetectedObject_Status) {
	x.xxx_hidden_Status = v
}

func (x *DetectedObject) HasClassification() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Classification != nil
}

func (x *DetectedObject) HasKinematics() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Kinematics != nil
}

func (x *DetectedObject) HasShape() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Shape != nil
}

func (x *DetectedObject) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *DetectedObject) ClearClassification() {
	x.xxx_hidden_Classification = nil
}

func (x *DetectedObject) ClearKinematics() {
	x.xxx_hidden_Kinematics = nil
}

func (x *DetectedObject) ClearShape() {
	x.xxx_hidden_Shape = nil
}

func (x *DetectedObject) ClearStatus() {
	x.xxx_hidden_Status = nil
}

type DetectedObject_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Classification *DetectedObject_Classification
	Kinematics     *DetectedObject_Kinematics
	Shape          *DetectedObject_Shape
	Status         *DetectedObject_Status
}

func (b0 DetectedObject_builder) Build() *DetectedObject {
	m0 := &DetectedObject{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Classification = b.Classification
	x.xxx_hidden_Kinematics = b.Kinematics
	x.xxx_hidden_Shape = b.Shape
	x.xxx_hidden_Status = b.Status
	return m0
}

// / A deep learning object message.
type DeepLearningObject struct {
	state                     protoimpl.MessageState             `protogen:"opaque.v1"`
	xxx_hidden_Classification *DeepLearningObject_Classification `protobuf:"bytes,1,opt,name=classification,proto3" json:"classification,omitempty"`
	xxx_hidden_BoundingBox    *BoundingBox                       `protobuf:"bytes,2,opt,name=bounding_box,json=boundingBox,proto3" json:"bounding_box,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DeepLearningObject) Reset() {
	*x = DeepLearningObject{}
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepLearningObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepLearningObject) ProtoMessage() {}

func (x *DeepLearningObject) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeepLearningObject) GetClassification() *DeepLearningObject_Classification {
	if x != nil {
		return x.xxx_hidden_Classification
	}
	return nil
}

func (x *DeepLearningObject) GetBoundingBox() *BoundingBox {
	if x != nil {
		return x.xxx_hidden_BoundingBox
	}
	return nil
}

func (x *DeepLearningObject) SetClassification(v *DeepLearningObject_Classification) {
	x.xxx_hidden_Classification = v
}

func (x *DeepLearningObject) SetBoundingBox(v *BoundingBox) {
	x.xxx_hidden_BoundingBox = v
}

func (x *DeepLearningObject) HasClassification() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Classification != nil
}

func (x *DeepLearningObject) HasBoundingBox() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BoundingBox != nil
}

func (x *DeepLearningObject) ClearClassification() {
	x.xxx_hidden_Classification = nil
}

func (x *DeepLearningObject) ClearBoundingBox() {
	x.xxx_hidden_BoundingBox = nil
}

type DeepLearningObject_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The label of the detected object.
	Classification *DeepLearningObject_Classification
	// The bounding box of the detected object.
	BoundingBox *BoundingBox
}

func (b0 DeepLearningObject_builder) Build() *DeepLearningObject {
	m0 := &DeepLearningObject{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Classification = b.Classification
	x.xxx_hidden_BoundingBox = b.BoundingBox
	return m0
}

// A detection event message.
type DetectionEvent struct {
	state                             protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Objects                *[]*DetectedObject        `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	xxx_hidden_LabeledPointClouds     *[]*LabeledPointCloud     `protobuf:"bytes,2,rep,name=labeled_point_clouds,json=labeledPointClouds,proto3" json:"labeled_point_clouds,omitempty"`
	xxx_hidden_FrameInfo              *DetectionEvent_FrameInfo `protobuf:"bytes,3,opt,name=frame_info,json=frameInfo,proto3" json:"frame_info,omitempty"`
	xxx_hidden_RawDeepLearningObjects *[]*DeepLearningObject    `protobuf:"bytes,4,rep,name=raw_deep_learning_objects,json=rawDeepLearningObjects,proto3" json:"raw_deep_learning_objects,omitempty"`
	xxx_hidden_UnrecoveredObjectIds   []uint32                  `protobuf:"varint,5,rep,packed,name=unrecovered_object_ids,json=unrecoveredObjectIds,proto3" json:"unrecovered_object_ids,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *DetectionEvent) Reset() {
	*x = DetectionEvent{}
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionEvent) ProtoMessage() {}

func (x *DetectionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DetectionEvent) GetObjects() []*DetectedObject {
	if x != nil {
		if x.xxx_hidden_Objects != nil {
			return *x.xxx_hidden_Objects
		}
	}
	return nil
}

func (x *DetectionEvent) GetLabeledPointClouds() []*LabeledPointCloud {
	if x != nil {
		if x.xxx_hidden_LabeledPointClouds != nil {
			return *x.xxx_hidden_LabeledPointClouds
		}
	}
	return nil
}

func (x *DetectionEvent) GetFrameInfo() *DetectionEvent_FrameInfo {
	if x != nil {
		return x.xxx_hidden_FrameInfo
	}
	return nil
}

func (x *DetectionEvent) GetRawDeepLearningObjects() []*DeepLearningObject {
	if x != nil {
		if x.xxx_hidden_RawDeepLearningObjects != nil {
			return *x.xxx_hidden_RawDeepLearningObjects
		}
	}
	return nil
}

func (x *DetectionEvent) GetUnrecoveredObjectIds() []uint32 {
	if x != nil {
		return x.xxx_hidden_UnrecoveredObjectIds
	}
	return nil
}

func (x *DetectionEvent) SetObjects(v []*DetectedObject) {
	x.xxx_hidden_Objects = &v
}

func (x *DetectionEvent) SetLabeledPointClouds(v []*LabeledPointCloud) {
	x.xxx_hidden_LabeledPointClouds = &v
}

func (x *DetectionEvent) SetFrameInfo(v *DetectionEvent_FrameInfo) {
	x.xxx_hidden_FrameInfo = v
}

func (x *DetectionEvent) SetRawDeepLearningObjects(v []*DeepLearningObject) {
	x.xxx_hidden_RawDeepLearningObjects = &v
}

func (x *DetectionEvent) SetUnrecoveredObjectIds(v []uint32) {
	x.xxx_hidden_UnrecoveredObjectIds = v
}

func (x *DetectionEvent) HasFrameInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FrameInfo != nil
}

func (x *DetectionEvent) ClearFrameInfo() {
	x.xxx_hidden_FrameInfo = nil
}

type DetectionEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The detected objects.
	Objects []*DetectedObject
	// The labeled point clouds.
	LabeledPointClouds []*LabeledPointCloud
	// The frame info of the detection event.
	FrameInfo *DetectionEvent_FrameInfo
	// The raw deep learning bounding boxes.
	RawDeepLearningObjects []*DeepLearningObject
	// IDs of objects that were persisted but could not be matched
	// to a new detection within the recovery window.
	// Subscribers should remove these IDs from their cache.
	UnrecoveredObjectIds []uint32
}

func (b0 DetectionEvent_builder) Build() *DetectionEvent {
	m0 := &DetectionEvent{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Objects = &b.Objects
	x.xxx_hidden_LabeledPointClouds = &b.LabeledPointClouds
	x.xxx_hidden_FrameInfo = b.FrameInfo
	x.xxx_hidden_RawDeepLearningObjects = &b.RawDeepLearningObjects
	x.xxx_hidden_UnrecoveredObjectIds = b.UnrecoveredObjectIds
	return m0
}

type DetectedObject_Classification struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ClassLabel      ObjectLabel            `protobuf:"varint,1,opt,name=class_label,json=classLabel,proto3,enum=horus.pb.ObjectLabel" json:"class_label,omitempty"`
	xxx_hidden_ClassConfidence float32                `protobuf:"fixed32,2,opt,name=class_confidence,json=classConfidence,proto3" json:"class_confidence,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DetectedObject_Classification) Reset() {
	*x = DetectedObject_Classification{}
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectedObject_Classification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectedObject_Classification) ProtoMessage() {}

func (x *DetectedObject_Classification) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DetectedObject_Classification) GetClassLabel() ObjectLabel {
	if x != nil {
		return x.xxx_hidden_ClassLabel
	}
	return ObjectLabel_LABEL_UNSPECIFIED
}

func (x *DetectedObject_Classification) GetClassConfidence() float32 {
	if x != nil {
		return x.xxx_hidden_ClassConfidence
	}
	return 0
}

func (x *DetectedObject_Classification) SetClassLabel(v ObjectLabel) {
	x.xxx_hidden_ClassLabel = v
}

func (x *DetectedObject_Classification) SetClassConfidence(v float32) {
	x.xxx_hidden_ClassConfidence = v
}

type DetectedObject_Classification_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The label of the detected object.
	ClassLabel ObjectLabel
	// The confidence of the detected object.
	ClassConfidence float32
}

func (b0 DetectedObject_Classification_builder) Build() *DetectedObject_Classification {
	m0 := &DetectedObject_Classification{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ClassLabel = b.ClassLabel
	x.xxx_hidden_ClassConfidence = b.ClassConfidence
	return m0
}

type DetectedObject_Kinematics struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LinearVelocity *metadata_pb.Vector2F  `protobuf:"bytes,1,opt,name=linear_velocity,json=linearVelocity,proto3" json:"linear_velocity,omitempty"`
	xxx_hidden_YawRate        float32                `protobuf:"fixed32,2,opt,name=yaw_rate,json=yawRate,proto3,oneof" json:"yaw_rate,omitempty"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DetectedObject_Kinematics) Reset() {
	*x = DetectedObject_Kinematics{}
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectedObject_Kinematics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectedObject_Kinematics) ProtoMessage() {}

func (x *DetectedObject_Kinematics) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DetectedObject_Kinematics) GetLinearVelocity() *metadata_pb.Vector2F {
	if x != nil {
		return x.xxx_hidden_LinearVelocity
	}
	return nil
}

func (x *DetectedObject_Kinematics) GetYawRate() float32 {
	if x != nil {
		return x.xxx_hidden_YawRate
	}
	return 0
}

func (x *DetectedObject_Kinematics) SetLinearVelocity(v *metadata_pb.Vector2F) {
	x.xxx_hidden_LinearVelocity = v
}

func (x *DetectedObject_Kinematics) SetYawRate(v float32) {
	x.xxx_hidden_YawRate = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DetectedObject_Kinematics) HasLinearVelocity() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LinearVelocity != nil
}

func (x *DetectedObject_Kinematics) HasYawRate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DetectedObject_Kinematics) ClearLinearVelocity() {
	x.xxx_hidden_LinearVelocity = nil
}

func (x *DetectedObject_Kinematics) ClearYawRate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_YawRate = 0
}

type DetectedObject_Kinematics_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The (X, Y) linear velocity in m/s.
	LinearVelocity *metadata_pb.Vector2F
	// The optional yaw rate in radians.
	// The yaw rate is not set if the used tracker uses a constant velocity
	// motion model.
	YawRate *float32
}

func (b0 DetectedObject_Kinematics_builder) Build() *DetectedObject_Kinematics {
	m0 := &DetectedObject_Kinematics{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LinearVelocity = b.LinearVelocity
	if b.YawRate != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_YawRate = *b.YawRate
	}
	return m0
}

type DetectedObject_Shape struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BoundingBox      *BoundingBox           `protobuf:"bytes,1,opt,name=bounding_box,json=boundingBox,proto3" json:"bounding_box,omitempty"`
	xxx_hidden_TightBoundingBox *BoundingBox           `protobuf:"bytes,2,opt,name=tight_bounding_box,json=tightBoundingBox,proto3" json:"tight_bounding_box,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DetectedObject_Shape) Reset() {
	*x = DetectedObject_Shape{}
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectedObject_Shape) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectedObject_Shape) ProtoMessage() {}

func (x *DetectedObject_Shape) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DetectedObject_Shape) GetBoundingBox() *BoundingBox {
	if x != nil {
		return x.xxx_hidden_BoundingBox
	}
	return nil
}

func (x *DetectedObject_Shape) GetTightBoundingBox() *BoundingBox {
	if x != nil {
		return x.xxx_hidden_TightBoundingBox
	}
	return nil
}

func (x *DetectedObject_Shape) SetBoundingBox(v *BoundingBox) {
	x.xxx_hidden_BoundingBox = v
}

func (x *DetectedObject_Shape) SetTightBoundingBox(v *BoundingBox) {
	x.xxx_hidden_TightBoundingBox = v
}

func (x *DetectedObject_Shape) HasBoundingBox() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BoundingBox != nil
}

func (x *DetectedObject_Shape) HasTightBoundingBox() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TightBoundingBox != nil
}

func (x *DetectedObject_Shape) ClearBoundingBox() {
	x.xxx_hidden_BoundingBox = nil
}

func (x *DetectedObject_Shape) ClearTightBoundingBox() {
	x.xxx_hidden_TightBoundingBox = nil
}

type DetectedObject_Shape_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The bounding box of the detected object.
	BoundingBox *BoundingBox
	// The tight bounding box around the object points.
	TightBoundingBox *BoundingBox
}

func (b0 DetectedObject_Shape_builder) Build() *DetectedObject_Shape {
	m0 := &DetectedObject_Shape{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_BoundingBox = b.BoundingBox
	x.xxx_hidden_TightBoundingBox = b.TightBoundingBox
	return m0
}

type DetectedObject_Status struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	xxx_hidden_TrackingStatus TrackingStatus         `protobuf:"varint,2,opt,name=tracking_status,json=trackingStatus,proto3,enum=horus.pb.TrackingStatus" json:"tracking_status,omitempty"`
	xxx_hidden_LastSeen       *metadata_pb.Timestamp `protobuf:"bytes,3,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DetectedObject_Status) Reset() {
	*x = DetectedObject_Status{}
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectedObject_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectedObject_Status) ProtoMessage() {}

func (x *DetectedObject_Status) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DetectedObject_Status) GetId() uint32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *DetectedObject_Status) GetTrackingStatus() TrackingStatus {
	if x != nil {
		return x.xxx_hidden_TrackingStatus
	}
	return TrackingStatus_TRACKING_STATUS_UNSPECIFIED
}

func (x *DetectedObject_Status) GetLastSeen() *metadata_pb.Timestamp {
	if x != nil {
		return x.xxx_hidden_LastSeen
	}
	return nil
}

func (x *DetectedObject_Status) SetId(v uint32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *DetectedObject_Status) SetTrackingStatus(v TrackingStatus) {
	x.xxx_hidden_TrackingStatus = v
}

func (x *DetectedObject_Status) SetLastSeen(v *metadata_pb.Timestamp) {
	x.xxx_hidden_LastSeen = v
}

func (x *DetectedObject_Status) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DetectedObject_Status) HasLastSeen() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_LastSeen != nil
}

func (x *DetectedObject_Status) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *DetectedObject_Status) ClearLastSeen() {
	x.xxx_hidden_LastSeen = nil
}

type DetectedObject_Status_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The id of the detected object.
	// Set optional to avoid field ellision for id 0 after serialization.
	Id *uint32
	// The tracking status of the detected object.
	TrackingStatus TrackingStatus
	// The timestamp at which the detected object was last seen.
	LastSeen *metadata_pb.Timestamp
}

func (b0 DetectedObject_Status_builder) Build() *DetectedObject_Status {
	m0 := &DetectedObject_Status{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = *b.Id
	}
	x.xxx_hidden_TrackingStatus = b.TrackingStatus
	x.xxx_hidden_LastSeen = b.LastSeen
	return m0
}

type DeepLearningObject_Classification struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ClassLabel      ObjectLabel            `protobuf:"varint,1,opt,name=class_label,json=classLabel,proto3,enum=horus.pb.ObjectLabel" json:"class_label,omitempty"`
	xxx_hidden_ClassConfidence float32                `protobuf:"fixed32,2,opt,name=class_confidence,json=classConfidence,proto3" json:"class_confidence,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DeepLearningObject_Classification) Reset() {
	*x = DeepLearningObject_Classification{}
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeepLearningObject_Classification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeepLearningObject_Classification) ProtoMessage() {}

func (x *DeepLearningObject_Classification) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeepLearningObject_Classification) GetClassLabel() ObjectLabel {
	if x != nil {
		return x.xxx_hidden_ClassLabel
	}
	return ObjectLabel_LABEL_UNSPECIFIED
}

func (x *DeepLearningObject_Classification) GetClassConfidence() float32 {
	if x != nil {
		return x.xxx_hidden_ClassConfidence
	}
	return 0
}

func (x *DeepLearningObject_Classification) SetClassLabel(v ObjectLabel) {
	x.xxx_hidden_ClassLabel = v
}

func (x *DeepLearningObject_Classification) SetClassConfidence(v float32) {
	x.xxx_hidden_ClassConfidence = v
}

type DeepLearningObject_Classification_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The label of the detected object.
	ClassLabel ObjectLabel
	// The confidence of the detected object.
	ClassConfidence float32
}

func (b0 DeepLearningObject_Classification_builder) Build() *DeepLearningObject_Classification {
	m0 := &DeepLearningObject_Classification{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ClassLabel = b.ClassLabel
	x.xxx_hidden_ClassConfidence = b.ClassConfidence
	return m0
}

type DetectionEvent_FrameInfo struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FrameTimestamp *metadata_pb.Timestamp `protobuf:"bytes,1,opt,name=frame_timestamp,json=frameTimestamp,proto3" json:"frame_timestamp,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DetectionEvent_FrameInfo) Reset() {
	*x = DetectionEvent_FrameInfo{}
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionEvent_FrameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionEvent_FrameInfo) ProtoMessage() {}

func (x *DetectionEvent_FrameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_detection_service_detection_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DetectionEvent_FrameInfo) GetFrameTimestamp() *metadata_pb.Timestamp {
	if x != nil {
		return x.xxx_hidden_FrameTimestamp
	}
	return nil
}

func (x *DetectionEvent_FrameInfo) SetFrameTimestamp(v *metadata_pb.Timestamp) {
	x.xxx_hidden_FrameTimestamp = v
}

func (x *DetectionEvent_FrameInfo) HasFrameTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_FrameTimestamp != nil
}

func (x *DetectionEvent_FrameInfo) ClearFrameTimestamp() {
	x.xxx_hidden_FrameTimestamp = nil
}

type DetectionEvent_FrameInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The detection frame timestamp.
	FrameTimestamp *metadata_pb.Timestamp
}

func (b0 DetectionEvent_FrameInfo_builder) Build() *DetectionEvent_FrameInfo {
	m0 := &DetectionEvent_FrameInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FrameTimestamp = b.FrameTimestamp
	return m0
}

var File_horus_pb_detection_service_detection_proto protoreflect.FileDescriptor

var file_horus_pb_detection_service_detection_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x64, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x68, 0x6f,
	0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x1a, 0x1e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2f, 0x70, 0x62,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2f, 0x70, 0x62,
	0x2f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x0b, 0x42, 0x6f,
	0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x78, 0x12, 0x26, 0x0a, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e,
	0x70, 0x62, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x66, 0x52, 0x04, 0x62, 0x61, 0x73,
	0x65, 0x12, 0x26, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x33, 0x66, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x79, 0x61, 0x77,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x79, 0x61, 0x77, 0x22, 0x98, 0x01, 0x0a, 0x11,
	0x4c, 0x61, 0x62, 0x65, 0x6c, 0x65, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x75,
	0x64, 0x12, 0x35, 0x0a, 0x0b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x52, 0x0a, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x12, 0x4c, 0x0a, 0x18, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x74, 0x6f, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x68, 0x6f, 0x72,
	0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x14, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x54, 0x6f, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22, 0xa7, 0x06, 0x0a, 0x0e, 0x44, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x4f, 0x0a, 0x0e, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x43, 0x0a, 0x0a, 0x6b, 0x69,
	0x6e, 0x65, 0x6d, 0x61, 0x74, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x4b, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x74,
	0x69, 0x63, 0x73, 0x52, 0x0a, 0x6b, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x74, 0x69, 0x63, 0x73, 0x12,
	0x34, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e,
	0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x52, 0x05,
	0x73, 0x68, 0x61, 0x70, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62,
	0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x73,
	0x0a, 0x0e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x36, 0x0a, 0x0b, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62,
	0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x0a, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x0f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65,
	0x6e, 0x63, 0x65, 0x1a, 0x76, 0x0a, 0x0a, 0x4b, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x74, 0x69, 0x63,
	0x73, 0x12, 0x3b, 0x0a, 0x0f, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x5f, 0x76, 0x65, 0x6c, 0x6f,
	0x63, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x68, 0x6f, 0x72,
	0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x32, 0x66, 0x52, 0x0e,
	0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x56, 0x65, 0x6c, 0x6f, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1e,
	0x0a, 0x08, 0x79, 0x61, 0x77, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x48, 0x00, 0x52, 0x07, 0x79, 0x61, 0x77, 0x52, 0x61, 0x74, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0b,
	0x0a, 0x09, 0x5f, 0x79, 0x61, 0x77, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x1a, 0x86, 0x01, 0x0a, 0x05,
	0x53, 0x68, 0x61, 0x70, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x5f, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x68, 0x6f,
	0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42,
	0x6f, 0x78, 0x52, 0x0b, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x78, 0x12,
	0x43, 0x0a, 0x12, 0x74, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x5f, 0x62, 0x6f, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x68, 0x6f,
	0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42,
	0x6f, 0x78, 0x52, 0x10, 0x74, 0x69, 0x67, 0x68, 0x74, 0x42, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x42, 0x6f, 0x78, 0x1a, 0x99, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x02, 0x69,
	0x64, 0x88, 0x01, 0x01, 0x12, 0x41, 0x0a, 0x0f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e,
	0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e,
	0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f,
	0x73, 0x65, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x6f, 0x72,
	0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x53, 0x65, 0x65, 0x6e, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69, 0x64,
	0x22, 0x98, 0x02, 0x0a, 0x12, 0x44, 0x65, 0x65, 0x70, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e,
	0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x53, 0x0a, 0x0e, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x65, 0x70, 0x4c,
	0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x0c,
	0x62, 0x6f, 0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x62, 0x6f, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f,
	0x75, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x78, 0x52, 0x0b, 0x62, 0x6f, 0x75, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x42, 0x6f, 0x78, 0x1a, 0x73, 0x0a, 0x0e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x36, 0x0a, 0x0b, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e,
	0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x52, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x12, 0x29, 0x0a, 0x10, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x64,
	0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0f, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x22, 0xb0, 0x03, 0x0a, 0x0e,
	0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x32,
	0x0a, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x07, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x12, 0x4d, 0x0a, 0x14, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x65, 0x64, 0x5f, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x5f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x65, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x52, 0x12, 0x6c,
	0x61, 0x62, 0x65, 0x6c, 0x65, 0x64, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x75, 0x64,
	0x73, 0x12, 0x41, 0x0a, 0x0a, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62,
	0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x46, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x66, 0x72, 0x61, 0x6d, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x57, 0x0a, 0x19, 0x72, 0x61, 0x77, 0x5f, 0x64, 0x65, 0x65, 0x70,
	0x5f, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e,
	0x70, 0x62, 0x2e, 0x44, 0x65, 0x65, 0x70, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x16, 0x72, 0x61, 0x77, 0x44, 0x65, 0x65, 0x70, 0x4c, 0x65,
	0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x34, 0x0a,
	0x16, 0x75, 0x6e, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x14, 0x75,
	0x6e, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x64, 0x73, 0x1a, 0x49, 0x0a, 0x09, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x3c, 0x0a, 0x0f, 0x66, 0x72, 0x61, 0x6d, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x68, 0x6f, 0x72, 0x75,
	0x73, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e,
	0x66, 0x72, 0x61, 0x6d, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2a, 0x54,
	0x0a, 0x0b, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x15, 0x0a,
	0x11, 0x4c, 0x41, 0x42, 0x45, 0x4c, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x49, 0x53, 0x43, 0x10, 0x01, 0x12, 0x07,
	0x0a, 0x03, 0x43, 0x41, 0x52, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x59, 0x43, 0x4c, 0x49,
	0x53, 0x54, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x45, 0x44, 0x45, 0x53, 0x54, 0x52, 0x49,
	0x41, 0x4e, 0x10, 0x04, 0x2a, 0x6f, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x69, 0x6e, 0x67,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x1b, 0x54, 0x52, 0x41, 0x43, 0x4b, 0x49,
	0x4e, 0x47, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x41, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x41, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x52, 0x49,
	0x46, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x52, 0x41, 0x43, 0x4b,
	0x49, 0x4e, 0x47, 0x10, 0x04, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_horus_pb_detection_service_detection_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_horus_pb_detection_service_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_horus_pb_detection_service_detection_proto_goTypes = []any{
	(ObjectLabel)(0),                          // 0: horus.pb.ObjectLabel
	(TrackingStatus)(0),                       // 1: horus.pb.TrackingStatus
	(*BoundingBox)(nil),                       // 2: horus.pb.BoundingBox
	(*LabeledPointCloud)(nil),                 // 3: horus.pb.LabeledPointCloud
	(*DetectedObject)(nil),                    // 4: horus.pb.DetectedObject
	(*DeepLearningObject)(nil),                // 5: horus.pb.DeepLearningObject
	(*DetectionEvent)(nil),                    // 6: horus.pb.DetectionEvent
	(*DetectedObject_Classification)(nil),     // 7: horus.pb.DetectedObject.Classification
	(*DetectedObject_Kinematics)(nil),         // 8: horus.pb.DetectedObject.Kinematics
	(*DetectedObject_Shape)(nil),              // 9: horus.pb.DetectedObject.Shape
	(*DetectedObject_Status)(nil),             // 10: horus.pb.DetectedObject.Status
	(*DeepLearningObject_Classification)(nil), // 11: horus.pb.DeepLearningObject.Classification
	(*DetectionEvent_FrameInfo)(nil),          // 12: horus.pb.DetectionEvent.FrameInfo
	(*metadata_pb.Vector3F)(nil),              // 13: horus.pb.Vector3f
	(*point_message_pb.PointFrame)(nil),       // 14: horus.pb.PointFrame
	(*metadata_pb.UInt32List)(nil),            // 15: horus.pb.UInt32List
	(*metadata_pb.Vector2F)(nil),              // 16: horus.pb.Vector2f
	(*metadata_pb.Timestamp)(nil),             // 17: horus.pb.Timestamp
}
var file_horus_pb_detection_service_detection_proto_depIdxs = []int32{
	13, // 0: horus.pb.BoundingBox.base:type_name -> horus.pb.Vector3f
	13, // 1: horus.pb.BoundingBox.size:type_name -> horus.pb.Vector3f
	14, // 2: horus.pb.LabeledPointCloud.point_cloud:type_name -> horus.pb.PointFrame
	15, // 3: horus.pb.LabeledPointCloud.point_index_to_object_id:type_name -> horus.pb.UInt32List
	7,  // 4: horus.pb.DetectedObject.classification:type_name -> horus.pb.DetectedObject.Classification
	8,  // 5: horus.pb.DetectedObject.kinematics:type_name -> horus.pb.DetectedObject.Kinematics
	9,  // 6: horus.pb.DetectedObject.shape:type_name -> horus.pb.DetectedObject.Shape
	10, // 7: horus.pb.DetectedObject.status:type_name -> horus.pb.DetectedObject.Status
	11, // 8: horus.pb.DeepLearningObject.classification:type_name -> horus.pb.DeepLearningObject.Classification
	2,  // 9: horus.pb.DeepLearningObject.bounding_box:type_name -> horus.pb.BoundingBox
	4,  // 10: horus.pb.DetectionEvent.objects:type_name -> horus.pb.DetectedObject
	3,  // 11: horus.pb.DetectionEvent.labeled_point_clouds:type_name -> horus.pb.LabeledPointCloud
	12, // 12: horus.pb.DetectionEvent.frame_info:type_name -> horus.pb.DetectionEvent.FrameInfo
	5,  // 13: horus.pb.DetectionEvent.raw_deep_learning_objects:type_name -> horus.pb.DeepLearningObject
	0,  // 14: horus.pb.DetectedObject.Classification.class_label:type_name -> horus.pb.ObjectLabel
	16, // 15: horus.pb.DetectedObject.Kinematics.linear_velocity:type_name -> horus.pb.Vector2f
	2,  // 16: horus.pb.DetectedObject.Shape.bounding_box:type_name -> horus.pb.BoundingBox
	2,  // 17: horus.pb.DetectedObject.Shape.tight_bounding_box:type_name -> horus.pb.BoundingBox
	1,  // 18: horus.pb.DetectedObject.Status.tracking_status:type_name -> horus.pb.TrackingStatus
	17, // 19: horus.pb.DetectedObject.Status.last_seen:type_name -> horus.pb.Timestamp
	0,  // 20: horus.pb.DeepLearningObject.Classification.class_label:type_name -> horus.pb.ObjectLabel
	17, // 21: horus.pb.DetectionEvent.FrameInfo.frame_timestamp:type_name -> horus.pb.Timestamp
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_horus_pb_detection_service_detection_proto_init() }
func file_horus_pb_detection_service_detection_proto_init() {
	if File_horus_pb_detection_service_detection_proto != nil {
		return
	}
	file_horus_pb_detection_service_detection_proto_msgTypes[6].OneofWrappers = []any{}
	file_horus_pb_detection_service_detection_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_horus_pb_detection_service_detection_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_horus_pb_detection_service_detection_proto_goTypes,
		DependencyIndexes: file_horus_pb_detection_service_detection_proto_depIdxs,
		EnumInfos:         file_horus_pb_detection_service_detection_proto_enumTypes,
		MessageInfos:      file_horus_pb_detection_service_detection_proto_msgTypes,
	}.Build()
	File_horus_pb_detection_service_detection_proto = out.File
	file_horus_pb_detection_service_detection_proto_rawDesc = nil
	file_horus_pb_detection_service_detection_proto_goTypes = nil
	file_horus_pb_detection_service_detection_proto_depIdxs = nil
}
