# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: horus/pb/resources.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'horus/pb/resources.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18horus/pb/resources.proto\x12\x08horus.pb\"=\n\x0eGpuProcessInfo\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12\x1e\n\x16gpu_memory_usage_bytes\x18\x02 \x01(\x04\"\xd4\x01\n\x07GpuInfo\x12\x0e\n\x06gpu_id\x18\x01 \x01(\r\x12\x10\n\x08gpu_name\x18\x02 \x01(\t\x12\x1b\n\x13temperature_celsius\x18\x03 \x01(\r\x12\x1e\n\x16utilization_percentage\x18\x04 \x01(\r\x12\x19\n\x11memory_used_bytes\x18\x05 \x01(\x04\x12\x1a\n\x12memory_total_bytes\x18\x06 \x01(\x04\x12\x33\n\x11running_processes\x18\x07 \x03(\x0b\x32\x18.horus.pb.GpuProcessInfo\"M\n\x11\x43puAndMemoryUsage\x12\x1c\n\x14\x63pu_usage_percentage\x18\x01 \x01(\r\x12\x1a\n\x12memory_usage_bytes\x18\x02 \x01(\x04\"\x9c\x01\n\rResourceUsage\x12,\n\x07process\x18\x01 \x01(\x0b\x32\x1b.horus.pb.CpuAndMemoryUsage\x12)\n\x04host\x18\x02 \x01(\x0b\x32\x1b.horus.pb.CpuAndMemoryUsage\x12\x1f\n\x04gpus\x18\x03 \x03(\x0b\x32\x11.horus.pb.GpuInfo\x12\x11\n\tcpu_cores\x18\x04 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'horus.pb.resources_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GPUPROCESSINFO']._serialized_start=38
  _globals['_GPUPROCESSINFO']._serialized_end=99
  _globals['_GPUINFO']._serialized_start=102
  _globals['_GPUINFO']._serialized_end=314
  _globals['_CPUANDMEMORYUSAGE']._serialized_start=316
  _globals['_CPUANDMEMORYUSAGE']._serialized_end=393
  _globals['_RESOURCEUSAGE']._serialized_start=396
  _globals['_RESOURCEUSAGE']._serialized_end=552
# @@protoc_insertion_point(module_scope)
