#ifndef HORUS_PB_RESOURCES_PB_H_
#define HORUS_PB_RESOURCES_PB_H_

/// @file
///
/// C++ type definitions for Protobuf messages in `horus/pb/resources.proto`.
///
/// Generated by `/opt/actions-runner/_work/horus/horus/common/tools/sdk/pb.ts`.

#include <bitset>
#include <cstdint>
#include <utility>

#include "horus/attributes.h"
#include "horus/internal/attributes.h"
#include "horus/pb/cow_bytes.h"
#include "horus/pb/cow_repeated.h"
#include "horus/pb/message.h"
#include "horus/pb/serialize.h"
#include "horus/strings/string_view.h"

#if HORUS_SDK_USE_PB_NAMESPACE_ALIAS
#include "horus/pb/alias.h"  // IWYU pragma: export
#endif

// NOLINTBEGIN(readability-identifier-length)

namespace horus {
namespace sdk {
namespace pb {

// MARK: Message forward declarations

class GpuProcessInfo;
class GpuInfo;
class CpuAndMemoryUsage;
class ResourceUsage;

// MARK: Message declarations

/// No documentation.
///
/// Source: horus/pb/resources.proto:5:1
class GpuProcessInfo final : public PbMessage {
 public:

  /// Constructs a default-initialized `GpuProcessInfo`.
  GpuProcessInfo() noexcept = default;

  /// Move constructor.
  GpuProcessInfo(GpuProcessInfo&&) noexcept = default;
  /// Move assignment operator.
  GpuProcessInfo& operator=(GpuProcessInfo&&) noexcept = default;

  /// Constructs a clone of `other`.
  ///
  /// @throws std::bad_alloc If `other` owns heap-allocated data which could not be cloned due to a
  /// lack of available memory.
  explicit GpuProcessInfo(const GpuProcessInfo& other) noexcept(false);  // NOLINT(*-explicit-*)

  /// Cannot copy-assign to avoid implicit allocations.
  GpuProcessInfo& operator=(const GpuProcessInfo&) = delete;

  /// Default destructor.
  ~GpuProcessInfo() noexcept final = default;

  /// Creates a `GpuProcessInfo` whose contents are read from `reader`.
  ///
  /// @throws InvalidProtobufMessage If the `reader` contains an invalid Protobuf message.
  explicit GpuProcessInfo(PbReader& reader) noexcept(false) : PbMessage{} {
    DeserializeFrom(reader);
  }

  /// Serializes the message to `writer`.
  ///
  /// @throws std::bad_alloc If the resulting buffer failed to allocate.
  void SerializeTo(PbWriter& writer) const noexcept(false) final;

  /// Deserializes the message from `reader`.
  ///
  /// @throws InvalidProtobufMessage If the `reader` contains an invalid Protobuf message.
  void DeserializeFrom(PbReader& reader) noexcept(false) final;

  /// Returns whether the message is empty.
  bool IsEmpty() const noexcept final { return set_fields_.none(); }

  /// The full name of the message: `horus.pb.GpuProcessInfo`.
  static constexpr StringView TypeName() noexcept { return "horus.pb.GpuProcessInfo"; }

  /// The full name of the message: `horus.pb.GpuProcessInfo`.
  StringView MessageTypeName() const noexcept final { return TypeName(); }

  // Field `pid` (no 1).
  // -----

  /// No documentation.
  ///
  /// Field no: 1.
  constexpr std::uint32_t pid() const& noexcept HORUS_LIFETIME_BOUND {
    return pid_;
  }

  /// No documentation.
  ///
  /// Field no: 1.
  std::uint32_t& mutable_pid() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[0] = true;
    return pid_;
  }

  /// Returns whether `pid` (no 1) is set.
  constexpr bool has_pid() const noexcept { return set_fields_[0]; }

  /// Clears `pid` (no 1).
  void clear_pid() & noexcept {
    set_fields_[0] = false;
    pid_ = {};
  }

  /// Sets `pid` (no 1) and returns `*this`.
  GpuProcessInfo& set_pid(std::uint32_t pid) & noexcept {
    set_fields_[0] = true;
    pid_ = pid;
    return *this;
  }
  /// Sets `pid` (no 1) and returns `*this`.
  GpuProcessInfo&& set_pid(std::uint32_t pid) && noexcept {
    return std::move(set_pid(pid));
  }

  // Field `gpu_memory_usage_bytes` (no 2).
  // -----

  /// No documentation.
  ///
  /// Field no: 2.
  constexpr std::uint64_t gpu_memory_usage_bytes() const& noexcept HORUS_LIFETIME_BOUND {
    return gpu_memory_usage_bytes_;
  }

  /// No documentation.
  ///
  /// Field no: 2.
  std::uint64_t& mutable_gpu_memory_usage_bytes() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[1] = true;
    return gpu_memory_usage_bytes_;
  }

  /// Returns whether `gpu_memory_usage_bytes` (no 2) is set.
  constexpr bool has_gpu_memory_usage_bytes() const noexcept { return set_fields_[1]; }

  /// Clears `gpu_memory_usage_bytes` (no 2).
  void clear_gpu_memory_usage_bytes() & noexcept {
    set_fields_[1] = false;
    gpu_memory_usage_bytes_ = {};
  }

  /// Sets `gpu_memory_usage_bytes` (no 2) and returns `*this`.
  GpuProcessInfo& set_gpu_memory_usage_bytes(std::uint64_t gpu_memory_usage_bytes) & noexcept {
    set_fields_[1] = true;
    gpu_memory_usage_bytes_ = gpu_memory_usage_bytes;
    return *this;
  }
  /// Sets `gpu_memory_usage_bytes` (no 2) and returns `*this`.
  GpuProcessInfo&& set_gpu_memory_usage_bytes(std::uint64_t gpu_memory_usage_bytes) && noexcept {
    return std::move(set_gpu_memory_usage_bytes(gpu_memory_usage_bytes));
  }

 private:
  /// @see pid()
  std::uint32_t pid_{};
  /// @see gpu_memory_usage_bytes()
  std::uint64_t gpu_memory_usage_bytes_{};

  /// The set of fields that have been given an explicit value.
  std::bitset<2> set_fields_;
};

/// No documentation.
///
/// Source: horus/pb/resources.proto:10:1
class GpuInfo final : public PbMessage {
 public:

  /// Constructs a default-initialized `GpuInfo`.
  GpuInfo() noexcept = default;

  /// Move constructor.
  GpuInfo(GpuInfo&&) noexcept = default;
  /// Move assignment operator.
  GpuInfo& operator=(GpuInfo&&) noexcept = default;

  /// Constructs a clone of `other`.
  ///
  /// @throws std::bad_alloc If `other` owns heap-allocated data which could not be cloned due to a
  /// lack of available memory.
  explicit GpuInfo(const GpuInfo& other) noexcept(false);  // NOLINT(*-explicit-*)

  /// Cannot copy-assign to avoid implicit allocations.
  GpuInfo& operator=(const GpuInfo&) = delete;

  /// Default destructor.
  ~GpuInfo() noexcept final = default;

  /// Creates a `GpuInfo` whose contents are read from `reader`.
  ///
  /// @throws InvalidProtobufMessage If the `reader` contains an invalid Protobuf message.
  explicit GpuInfo(PbReader& reader) noexcept(false) : PbMessage{} {
    DeserializeFrom(reader);
  }

  /// Serializes the message to `writer`.
  ///
  /// @throws std::bad_alloc If the resulting buffer failed to allocate.
  void SerializeTo(PbWriter& writer) const noexcept(false) final;

  /// Deserializes the message from `reader`.
  ///
  /// @throws InvalidProtobufMessage If the `reader` contains an invalid Protobuf message.
  void DeserializeFrom(PbReader& reader) noexcept(false) final;

  /// Returns whether the message is empty.
  bool IsEmpty() const noexcept final { return set_fields_.none(); }

  /// The full name of the message: `horus.pb.GpuInfo`.
  static constexpr StringView TypeName() noexcept { return "horus.pb.GpuInfo"; }

  /// The full name of the message: `horus.pb.GpuInfo`.
  StringView MessageTypeName() const noexcept final { return TypeName(); }

  // Field `gpu_id` (no 1).
  // -----

  /// No documentation.
  ///
  /// Field no: 1.
  constexpr std::uint32_t gpu_id() const& noexcept HORUS_LIFETIME_BOUND {
    return gpu_id_;
  }

  /// No documentation.
  ///
  /// Field no: 1.
  std::uint32_t& mutable_gpu_id() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[0] = true;
    return gpu_id_;
  }

  /// Returns whether `gpu_id` (no 1) is set.
  constexpr bool has_gpu_id() const noexcept { return set_fields_[0]; }

  /// Clears `gpu_id` (no 1).
  void clear_gpu_id() & noexcept {
    set_fields_[0] = false;
    gpu_id_ = {};
  }

  /// Sets `gpu_id` (no 1) and returns `*this`.
  GpuInfo& set_gpu_id(std::uint32_t gpu_id) & noexcept {
    set_fields_[0] = true;
    gpu_id_ = gpu_id;
    return *this;
  }
  /// Sets `gpu_id` (no 1) and returns `*this`.
  GpuInfo&& set_gpu_id(std::uint32_t gpu_id) && noexcept {
    return std::move(set_gpu_id(gpu_id));
  }

  // Field `gpu_name` (no 2).
  // -----

  /// No documentation.
  ///
  /// Field no: 2.
  constexpr const CowBytes& gpu_name() const& noexcept HORUS_LIFETIME_BOUND {
    return gpu_name_;
  }

  /// If `gpu_name` is set, moves it out of the message (without marking it as unset).
  ///
  /// Otherwise, returns a default-initialized value.
  ///
  /// Field no: 2.
  CowBytes gpu_name() && noexcept {
    if (!set_fields_[1]) {
      return {};
    }
    return std::move(gpu_name_);
  }

  /// No documentation.
  ///
  /// Field no: 2.
  CowBytes& mutable_gpu_name() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[1] = true;
    return gpu_name_;
  }

  /// Returns whether `gpu_name` (no 2) is set.
  constexpr bool has_gpu_name() const noexcept { return set_fields_[1]; }

  /// Clears `gpu_name` (no 2).
  void clear_gpu_name() & noexcept {
    set_fields_[1] = false;
    gpu_name_ = {};
  }

  /// Sets `gpu_name` (no 2) and returns `*this`.
  GpuInfo& set_gpu_name(CowBytes&& gpu_name) & noexcept {
    set_fields_[1] = true;
    gpu_name_ = std::move(gpu_name);
    return *this;
  }
  /// Sets `gpu_name` (no 2) and returns `*this`.
  GpuInfo&& set_gpu_name(CowBytes&& gpu_name) && noexcept {
    return std::move(set_gpu_name(std::move(gpu_name)));
  }

  // Field `temperature_celsius` (no 3).
  // -----

  /// No documentation.
  ///
  /// Field no: 3.
  constexpr std::uint32_t temperature_celsius() const& noexcept HORUS_LIFETIME_BOUND {
    return temperature_celsius_;
  }

  /// No documentation.
  ///
  /// Field no: 3.
  std::uint32_t& mutable_temperature_celsius() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[2] = true;
    return temperature_celsius_;
  }

  /// Returns whether `temperature_celsius` (no 3) is set.
  constexpr bool has_temperature_celsius() const noexcept { return set_fields_[2]; }

  /// Clears `temperature_celsius` (no 3).
  void clear_temperature_celsius() & noexcept {
    set_fields_[2] = false;
    temperature_celsius_ = {};
  }

  /// Sets `temperature_celsius` (no 3) and returns `*this`.
  GpuInfo& set_temperature_celsius(std::uint32_t temperature_celsius) & noexcept {
    set_fields_[2] = true;
    temperature_celsius_ = temperature_celsius;
    return *this;
  }
  /// Sets `temperature_celsius` (no 3) and returns `*this`.
  GpuInfo&& set_temperature_celsius(std::uint32_t temperature_celsius) && noexcept {
    return std::move(set_temperature_celsius(temperature_celsius));
  }

  // Field `utilization_percentage` (no 4).
  // -----

  /// No documentation.
  ///
  /// Field no: 4.
  constexpr std::uint32_t utilization_percentage() const& noexcept HORUS_LIFETIME_BOUND {
    return utilization_percentage_;
  }

  /// No documentation.
  ///
  /// Field no: 4.
  std::uint32_t& mutable_utilization_percentage() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[3] = true;
    return utilization_percentage_;
  }

  /// Returns whether `utilization_percentage` (no 4) is set.
  constexpr bool has_utilization_percentage() const noexcept { return set_fields_[3]; }

  /// Clears `utilization_percentage` (no 4).
  void clear_utilization_percentage() & noexcept {
    set_fields_[3] = false;
    utilization_percentage_ = {};
  }

  /// Sets `utilization_percentage` (no 4) and returns `*this`.
  GpuInfo& set_utilization_percentage(std::uint32_t utilization_percentage) & noexcept {
    set_fields_[3] = true;
    utilization_percentage_ = utilization_percentage;
    return *this;
  }
  /// Sets `utilization_percentage` (no 4) and returns `*this`.
  GpuInfo&& set_utilization_percentage(std::uint32_t utilization_percentage) && noexcept {
    return std::move(set_utilization_percentage(utilization_percentage));
  }

  // Field `memory_used_bytes` (no 5).
  // -----

  /// No documentation.
  ///
  /// Field no: 5.
  constexpr std::uint64_t memory_used_bytes() const& noexcept HORUS_LIFETIME_BOUND {
    return memory_used_bytes_;
  }

  /// No documentation.
  ///
  /// Field no: 5.
  std::uint64_t& mutable_memory_used_bytes() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[4] = true;
    return memory_used_bytes_;
  }

  /// Returns whether `memory_used_bytes` (no 5) is set.
  constexpr bool has_memory_used_bytes() const noexcept { return set_fields_[4]; }

  /// Clears `memory_used_bytes` (no 5).
  void clear_memory_used_bytes() & noexcept {
    set_fields_[4] = false;
    memory_used_bytes_ = {};
  }

  /// Sets `memory_used_bytes` (no 5) and returns `*this`.
  GpuInfo& set_memory_used_bytes(std::uint64_t memory_used_bytes) & noexcept {
    set_fields_[4] = true;
    memory_used_bytes_ = memory_used_bytes;
    return *this;
  }
  /// Sets `memory_used_bytes` (no 5) and returns `*this`.
  GpuInfo&& set_memory_used_bytes(std::uint64_t memory_used_bytes) && noexcept {
    return std::move(set_memory_used_bytes(memory_used_bytes));
  }

  // Field `memory_total_bytes` (no 6).
  // -----

  /// No documentation.
  ///
  /// Field no: 6.
  constexpr std::uint64_t memory_total_bytes() const& noexcept HORUS_LIFETIME_BOUND {
    return memory_total_bytes_;
  }

  /// No documentation.
  ///
  /// Field no: 6.
  std::uint64_t& mutable_memory_total_bytes() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[5] = true;
    return memory_total_bytes_;
  }

  /// Returns whether `memory_total_bytes` (no 6) is set.
  constexpr bool has_memory_total_bytes() const noexcept { return set_fields_[5]; }

  /// Clears `memory_total_bytes` (no 6).
  void clear_memory_total_bytes() & noexcept {
    set_fields_[5] = false;
    memory_total_bytes_ = {};
  }

  /// Sets `memory_total_bytes` (no 6) and returns `*this`.
  GpuInfo& set_memory_total_bytes(std::uint64_t memory_total_bytes) & noexcept {
    set_fields_[5] = true;
    memory_total_bytes_ = memory_total_bytes;
    return *this;
  }
  /// Sets `memory_total_bytes` (no 6) and returns `*this`.
  GpuInfo&& set_memory_total_bytes(std::uint64_t memory_total_bytes) && noexcept {
    return std::move(set_memory_total_bytes(memory_total_bytes));
  }

  // Field `running_processes` (no 7).
  // -----

  /// No documentation.
  ///
  /// Field no: 7.
  constexpr const CowRepeated<GpuProcessInfo>& running_processes() const& noexcept HORUS_LIFETIME_BOUND {
    return running_processes_;
  }

  /// If `running_processes` is set, moves it out of the message (without marking it as unset).
  ///
  /// Otherwise, returns a default-initialized value.
  ///
  /// Field no: 7.
  CowRepeated<GpuProcessInfo> running_processes() && noexcept {
    if (!set_fields_[6]) {
      return {};
    }
    return std::move(running_processes_);
  }

  /// No documentation.
  ///
  /// Field no: 7.
  CowRepeated<GpuProcessInfo>& mutable_running_processes() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[6] = true;
    return running_processes_;
  }

  /// Returns whether `running_processes` (no 7) is set.
  constexpr bool has_running_processes() const noexcept { return set_fields_[6]; }

  /// Clears `running_processes` (no 7).
  void clear_running_processes() & noexcept {
    set_fields_[6] = false;
    running_processes_ = {};
  }

  /// Sets `running_processes` (no 7) and returns `*this`.
  GpuInfo& set_running_processes(CowRepeated<GpuProcessInfo>&& running_processes) & noexcept {
    set_fields_[6] = true;
    running_processes_ = std::move(running_processes);
    return *this;
  }
  /// Sets `running_processes` (no 7) and returns `*this`.
  GpuInfo&& set_running_processes(CowRepeated<GpuProcessInfo>&& running_processes) && noexcept {
    return std::move(set_running_processes(std::move(running_processes)));
  }

 private:
  /// @see gpu_id()
  std::uint32_t gpu_id_{};
  /// @see gpu_name()
  CowBytes gpu_name_{};
  /// @see temperature_celsius()
  std::uint32_t temperature_celsius_{};
  /// @see utilization_percentage()
  std::uint32_t utilization_percentage_{};
  /// @see memory_used_bytes()
  std::uint64_t memory_used_bytes_{};
  /// @see memory_total_bytes()
  std::uint64_t memory_total_bytes_{};
  /// @see running_processes()
  CowRepeated<GpuProcessInfo> running_processes_{};

  /// The set of fields that have been given an explicit value.
  std::bitset<7> set_fields_;
};

/// No documentation.
///
/// Source: horus/pb/resources.proto:22:1
class CpuAndMemoryUsage final : public PbMessage {
 public:

  /// Constructs a default-initialized `CpuAndMemoryUsage`.
  CpuAndMemoryUsage() noexcept = default;

  /// Move constructor.
  CpuAndMemoryUsage(CpuAndMemoryUsage&&) noexcept = default;
  /// Move assignment operator.
  CpuAndMemoryUsage& operator=(CpuAndMemoryUsage&&) noexcept = default;

  /// Constructs a clone of `other`.
  ///
  /// @throws std::bad_alloc If `other` owns heap-allocated data which could not be cloned due to a
  /// lack of available memory.
  explicit CpuAndMemoryUsage(const CpuAndMemoryUsage& other) noexcept(false);  // NOLINT(*-explicit-*)

  /// Cannot copy-assign to avoid implicit allocations.
  CpuAndMemoryUsage& operator=(const CpuAndMemoryUsage&) = delete;

  /// Default destructor.
  ~CpuAndMemoryUsage() noexcept final = default;

  /// Creates a `CpuAndMemoryUsage` whose contents are read from `reader`.
  ///
  /// @throws InvalidProtobufMessage If the `reader` contains an invalid Protobuf message.
  explicit CpuAndMemoryUsage(PbReader& reader) noexcept(false) : PbMessage{} {
    DeserializeFrom(reader);
  }

  /// Serializes the message to `writer`.
  ///
  /// @throws std::bad_alloc If the resulting buffer failed to allocate.
  void SerializeTo(PbWriter& writer) const noexcept(false) final;

  /// Deserializes the message from `reader`.
  ///
  /// @throws InvalidProtobufMessage If the `reader` contains an invalid Protobuf message.
  void DeserializeFrom(PbReader& reader) noexcept(false) final;

  /// Returns whether the message is empty.
  bool IsEmpty() const noexcept final { return set_fields_.none(); }

  /// The full name of the message: `horus.pb.CpuAndMemoryUsage`.
  static constexpr StringView TypeName() noexcept { return "horus.pb.CpuAndMemoryUsage"; }

  /// The full name of the message: `horus.pb.CpuAndMemoryUsage`.
  StringView MessageTypeName() const noexcept final { return TypeName(); }

  // Field `cpu_usage_percentage` (no 1).
  // -----

  /// CPU usage in the htop convention: 100% means one full core busy.
  ///  A multi-threaded process can exceed 100%. Divide by `cpu_cores` from the
  ///  parent ResourceUsage to obtain a machine-normalized (0-100%) percentage.
  ///
  /// Field no: 1.
  constexpr std::uint32_t cpu_usage_percentage() const& noexcept HORUS_LIFETIME_BOUND {
    return cpu_usage_percentage_;
  }

  /// CPU usage in the htop convention: 100% means one full core busy.
  ///  A multi-threaded process can exceed 100%. Divide by `cpu_cores` from the
  ///  parent ResourceUsage to obtain a machine-normalized (0-100%) percentage.
  ///
  /// Field no: 1.
  std::uint32_t& mutable_cpu_usage_percentage() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[0] = true;
    return cpu_usage_percentage_;
  }

  /// Returns whether `cpu_usage_percentage` (no 1) is set.
  constexpr bool has_cpu_usage_percentage() const noexcept { return set_fields_[0]; }

  /// Clears `cpu_usage_percentage` (no 1).
  void clear_cpu_usage_percentage() & noexcept {
    set_fields_[0] = false;
    cpu_usage_percentage_ = {};
  }

  /// Sets `cpu_usage_percentage` (no 1) and returns `*this`.
  CpuAndMemoryUsage& set_cpu_usage_percentage(std::uint32_t cpu_usage_percentage) & noexcept {
    set_fields_[0] = true;
    cpu_usage_percentage_ = cpu_usage_percentage;
    return *this;
  }
  /// Sets `cpu_usage_percentage` (no 1) and returns `*this`.
  CpuAndMemoryUsage&& set_cpu_usage_percentage(std::uint32_t cpu_usage_percentage) && noexcept {
    return std::move(set_cpu_usage_percentage(cpu_usage_percentage));
  }

  // Field `memory_usage_bytes` (no 2).
  // -----

  /// No documentation.
  ///
  /// Field no: 2.
  constexpr std::uint64_t memory_usage_bytes() const& noexcept HORUS_LIFETIME_BOUND {
    return memory_usage_bytes_;
  }

  /// No documentation.
  ///
  /// Field no: 2.
  std::uint64_t& mutable_memory_usage_bytes() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[1] = true;
    return memory_usage_bytes_;
  }

  /// Returns whether `memory_usage_bytes` (no 2) is set.
  constexpr bool has_memory_usage_bytes() const noexcept { return set_fields_[1]; }

  /// Clears `memory_usage_bytes` (no 2).
  void clear_memory_usage_bytes() & noexcept {
    set_fields_[1] = false;
    memory_usage_bytes_ = {};
  }

  /// Sets `memory_usage_bytes` (no 2) and returns `*this`.
  CpuAndMemoryUsage& set_memory_usage_bytes(std::uint64_t memory_usage_bytes) & noexcept {
    set_fields_[1] = true;
    memory_usage_bytes_ = memory_usage_bytes;
    return *this;
  }
  /// Sets `memory_usage_bytes` (no 2) and returns `*this`.
  CpuAndMemoryUsage&& set_memory_usage_bytes(std::uint64_t memory_usage_bytes) && noexcept {
    return std::move(set_memory_usage_bytes(memory_usage_bytes));
  }

 private:
  /// @see cpu_usage_percentage()
  std::uint32_t cpu_usage_percentage_{};
  /// @see memory_usage_bytes()
  std::uint64_t memory_usage_bytes_{};

  /// The set of fields that have been given an explicit value.
  std::bitset<2> set_fields_;
};

/// No documentation.
///
/// Source: horus/pb/resources.proto:30:1
class ResourceUsage final : public PbMessage {
 public:

  /// Constructs a default-initialized `ResourceUsage`.
  ResourceUsage() noexcept = default;

  /// Move constructor.
  ResourceUsage(ResourceUsage&&) noexcept = default;
  /// Move assignment operator.
  ResourceUsage& operator=(ResourceUsage&&) noexcept = default;

  /// Constructs a clone of `other`.
  ///
  /// @throws std::bad_alloc If `other` owns heap-allocated data which could not be cloned due to a
  /// lack of available memory.
  explicit ResourceUsage(const ResourceUsage& other) noexcept(false);  // NOLINT(*-explicit-*)

  /// Cannot copy-assign to avoid implicit allocations.
  ResourceUsage& operator=(const ResourceUsage&) = delete;

  /// Default destructor.
  ~ResourceUsage() noexcept final = default;

  /// Creates a `ResourceUsage` whose contents are read from `reader`.
  ///
  /// @throws InvalidProtobufMessage If the `reader` contains an invalid Protobuf message.
  explicit ResourceUsage(PbReader& reader) noexcept(false) : PbMessage{} {
    DeserializeFrom(reader);
  }

  /// Serializes the message to `writer`.
  ///
  /// @throws std::bad_alloc If the resulting buffer failed to allocate.
  void SerializeTo(PbWriter& writer) const noexcept(false) final;

  /// Deserializes the message from `reader`.
  ///
  /// @throws InvalidProtobufMessage If the `reader` contains an invalid Protobuf message.
  void DeserializeFrom(PbReader& reader) noexcept(false) final;

  /// Returns whether the message is empty.
  bool IsEmpty() const noexcept final { return set_fields_.none(); }

  /// The full name of the message: `horus.pb.ResourceUsage`.
  static constexpr StringView TypeName() noexcept { return "horus.pb.ResourceUsage"; }

  /// The full name of the message: `horus.pb.ResourceUsage`.
  StringView MessageTypeName() const noexcept final { return TypeName(); }

  // Field `process` (no 1).
  // -----

  /// No documentation.
  ///
  /// Field no: 1.
  constexpr const CpuAndMemoryUsage& process() const& noexcept HORUS_LIFETIME_BOUND {
    return process_;
  }

  /// If `process` is set, moves it out of the message (without marking it as unset).
  ///
  /// Otherwise, returns a default-initialized value.
  ///
  /// Field no: 1.
  CpuAndMemoryUsage process() && noexcept {
    if (!set_fields_[0]) {
      return {};
    }
    return std::move(process_);
  }

  /// No documentation.
  ///
  /// Field no: 1.
  CpuAndMemoryUsage& mutable_process() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[0] = true;
    return process_;
  }

  /// Returns whether `process` (no 1) is set.
  constexpr bool has_process() const noexcept { return set_fields_[0]; }

  /// Clears `process` (no 1).
  void clear_process() & noexcept {
    set_fields_[0] = false;
    process_ = {};
  }

  /// Sets `process` (no 1) and returns `*this`.
  ResourceUsage& set_process(CpuAndMemoryUsage&& process) & noexcept {
    set_fields_[0] = true;
    process_ = std::move(process);
    return *this;
  }
  /// Sets `process` (no 1) and returns `*this`.
  ResourceUsage&& set_process(CpuAndMemoryUsage&& process) && noexcept {
    return std::move(set_process(std::move(process)));
  }

  // Field `host` (no 2).
  // -----

  /// No documentation.
  ///
  /// Field no: 2.
  constexpr const CpuAndMemoryUsage& host() const& noexcept HORUS_LIFETIME_BOUND {
    return host_;
  }

  /// If `host` is set, moves it out of the message (without marking it as unset).
  ///
  /// Otherwise, returns a default-initialized value.
  ///
  /// Field no: 2.
  CpuAndMemoryUsage host() && noexcept {
    if (!set_fields_[1]) {
      return {};
    }
    return std::move(host_);
  }

  /// No documentation.
  ///
  /// Field no: 2.
  CpuAndMemoryUsage& mutable_host() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[1] = true;
    return host_;
  }

  /// Returns whether `host` (no 2) is set.
  constexpr bool has_host() const noexcept { return set_fields_[1]; }

  /// Clears `host` (no 2).
  void clear_host() & noexcept {
    set_fields_[1] = false;
    host_ = {};
  }

  /// Sets `host` (no 2) and returns `*this`.
  ResourceUsage& set_host(CpuAndMemoryUsage&& host) & noexcept {
    set_fields_[1] = true;
    host_ = std::move(host);
    return *this;
  }
  /// Sets `host` (no 2) and returns `*this`.
  ResourceUsage&& set_host(CpuAndMemoryUsage&& host) && noexcept {
    return std::move(set_host(std::move(host)));
  }

  // Field `gpus` (no 3).
  // -----

  /// No documentation.
  ///
  /// Field no: 3.
  constexpr const CowRepeated<GpuInfo>& gpus() const& noexcept HORUS_LIFETIME_BOUND {
    return gpus_;
  }

  /// If `gpus` is set, moves it out of the message (without marking it as unset).
  ///
  /// Otherwise, returns a default-initialized value.
  ///
  /// Field no: 3.
  CowRepeated<GpuInfo> gpus() && noexcept {
    if (!set_fields_[2]) {
      return {};
    }
    return std::move(gpus_);
  }

  /// No documentation.
  ///
  /// Field no: 3.
  CowRepeated<GpuInfo>& mutable_gpus() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[2] = true;
    return gpus_;
  }

  /// Returns whether `gpus` (no 3) is set.
  constexpr bool has_gpus() const noexcept { return set_fields_[2]; }

  /// Clears `gpus` (no 3).
  void clear_gpus() & noexcept {
    set_fields_[2] = false;
    gpus_ = {};
  }

  /// Sets `gpus` (no 3) and returns `*this`.
  ResourceUsage& set_gpus(CowRepeated<GpuInfo>&& gpus) & noexcept {
    set_fields_[2] = true;
    gpus_ = std::move(gpus);
    return *this;
  }
  /// Sets `gpus` (no 3) and returns `*this`.
  ResourceUsage&& set_gpus(CowRepeated<GpuInfo>&& gpus) && noexcept {
    return std::move(set_gpus(std::move(gpus)));
  }

  // Field `cpu_cores` (no 4).
  // -----

  /// Number of logical CPU cores on the host. Use this to normalize
  ///  cpu_usage_percentage from htop-style to a 0-100% machine-level percentage.
  ///
  /// Field no: 4.
  constexpr std::uint32_t cpu_cores() const& noexcept HORUS_LIFETIME_BOUND {
    return cpu_cores_;
  }

  /// Number of logical CPU cores on the host. Use this to normalize
  ///  cpu_usage_percentage from htop-style to a 0-100% machine-level percentage.
  ///
  /// Field no: 4.
  std::uint32_t& mutable_cpu_cores() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[3] = true;
    return cpu_cores_;
  }

  /// Returns whether `cpu_cores` (no 4) is set.
  constexpr bool has_cpu_cores() const noexcept { return set_fields_[3]; }

  /// Clears `cpu_cores` (no 4).
  void clear_cpu_cores() & noexcept {
    set_fields_[3] = false;
    cpu_cores_ = {};
  }

  /// Sets `cpu_cores` (no 4) and returns `*this`.
  ResourceUsage& set_cpu_cores(std::uint32_t cpu_cores) & noexcept {
    set_fields_[3] = true;
    cpu_cores_ = cpu_cores;
    return *this;
  }
  /// Sets `cpu_cores` (no 4) and returns `*this`.
  ResourceUsage&& set_cpu_cores(std::uint32_t cpu_cores) && noexcept {
    return std::move(set_cpu_cores(cpu_cores));
  }

 private:
  /// @see process()
  CpuAndMemoryUsage process_{};
  /// @see host()
  CpuAndMemoryUsage host_{};
  /// @see gpus()
  CowRepeated<GpuInfo> gpus_{};
  /// @see cpu_cores()
  std::uint32_t cpu_cores_{};

  /// The set of fields that have been given an explicit value.
  std::bitset<4> set_fields_;
};

}  // namespace pb
}  // namespace sdk
}  // namespace horus

// NOLINTEND(readability-identifier-length)

#endif  // HORUS_PB_RESOURCES_PB_H_
