# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: horus/pb/status_service/service.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'horus/pb/status_service/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from horus.pb import rpc_pb2 as horus_dot_pb_dot_rpc__pb2
from horus.pb.status_service import messages_pb2 as horus_dot_pb_dot_status__service_dot_messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%horus/pb/status_service/service.proto\x12\x08horus.pb\x1a\x12horus/pb/rpc.proto\x1a&horus/pb/status_service/messages.proto\"\x13\n\x11GetVersionRequest\"8\n\x12GetVersionResponse\x12\"\n\x07version\x18\x01 \x01(\x0b\x32\x11.horus.pb.Version2\xd1\x01\n\rStatusService\x12w\n\nGetVersion\x12\x1b.horus.pb.GetVersionRequest\x1a\x1c.horus.pb.GetVersionResponse\".\xc2\xab\xb1.)\x08\x01\x12%Returns the current version of horus.\x1aG\xc2\xab\xb1.B\x08\x0f\x12>Service running in every binary, returning status information.b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'horus.pb.status_service.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSSERVICE']._loaded_options = None
  _globals['_STATUSSERVICE']._serialized_options = b'\302\253\261.B\010\017\022>Service running in every binary, returning status information.'
  _globals['_STATUSSERVICE'].methods_by_name['GetVersion']._loaded_options = None
  _globals['_STATUSSERVICE'].methods_by_name['GetVersion']._serialized_options = b'\302\253\261.)\010\001\022%Returns the current version of horus.'
  _globals['_GETVERSIONREQUEST']._serialized_start=111
  _globals['_GETVERSIONREQUEST']._serialized_end=130
  _globals['_GETVERSIONRESPONSE']._serialized_start=132
  _globals['_GETVERSIONRESPONSE']._serialized_end=188
  _globals['_STATUSSERVICE']._serialized_start=191
  _globals['_STATUSSERVICE']._serialized_end=400
# @@protoc_insertion_point(module_scope)
