#ifndef HORUS_PB_CONFIG_SCHEMA_ZONE_PB_H_
#define HORUS_PB_CONFIG_SCHEMA_ZONE_PB_H_

/// @file
///
/// C++ type definitions for Protobuf messages in `horus/pb/config/schema/zone.proto`.
///
/// Generated by `/opt/actions-runner/_work/horus/horus/common/tools/sdk/pb.ts`.

#include <bitset>
#include <cstdint>
#include <utility>

#include "horus/attributes.h"
#include "horus/internal/attributes.h"
#include "horus/pb/config/metadata_pb.h"
#include "horus/pb/cow_bytes.h"
#include "horus/pb/message.h"
#include "horus/pb/serialize.h"
#include "horus/pb/types.h"
#include "horus/strings/string_view.h"

#if HORUS_SDK_USE_PB_NAMESPACE_ALIAS
#include "horus/pb/alias.h"  // IWYU pragma: export
#endif

// NOLINTBEGIN(readability-identifier-length)

namespace horus {
namespace sdk {
namespace pb {

// MARK: Enum declarations

/// No documentation.
///
/// Source: horus/pb/config/schema/zone.proto:7:1
enum class ZoneType : PbEnum {  // NOLINT(*-enum-size)
  /// No documentation.
  kUnspecified = 0,
  /// No documentation.
  kExclusion = 1,
  /// No documentation.
  kStaticDetection = 2,
  /// No documentation.
  kReflection = 3,
  /// No documentation.
  kStaticExclusion = 4,
  /// No documentation.
  kEvent = 5,

  /// Unknown value read from the wire.
  kUnknownWireValue = 6,
};

// MARK: Message forward declarations

class Zone;

// MARK: Message declarations

/// No documentation.
///
/// Source: horus/pb/config/schema/zone.proto:16:1
class Zone final : public PbMessage {
 public:

  /// Constructs a default-initialized `Zone`.
  Zone() noexcept = default;

  /// Move constructor.
  Zone(Zone&&) noexcept = default;
  /// Move assignment operator.
  Zone& operator=(Zone&&) noexcept = default;

  /// Constructs a clone of `other`.
  ///
  /// @throws std::bad_alloc If `other` owns heap-allocated data which could not be cloned due to a
  /// lack of available memory.
  explicit Zone(const Zone& other) noexcept(false);  // NOLINT(*-explicit-*)

  /// Cannot copy-assign to avoid implicit allocations.
  Zone& operator=(const Zone&) = delete;

  /// Default destructor.
  ~Zone() noexcept final = default;

  /// Creates a `Zone` whose contents are read from `reader`.
  ///
  /// @throws InvalidProtobufMessage If the `reader` contains an invalid Protobuf message.
  explicit Zone(PbReader& reader) noexcept(false) : PbMessage{} {
    DeserializeFrom(reader);
  }

  /// Serializes the message to `writer`.
  ///
  /// @throws std::bad_alloc If the resulting buffer failed to allocate.
  void SerializeTo(PbWriter& writer) const noexcept(false) final;

  /// Deserializes the message from `reader`.
  ///
  /// @throws InvalidProtobufMessage If the `reader` contains an invalid Protobuf message.
  void DeserializeFrom(PbReader& reader) noexcept(false) final;

  /// Returns whether the message is empty.
  bool IsEmpty() const noexcept final { return set_fields_.none(); }

  /// The full name of the message: `horus.pb.Zone`.
  static constexpr StringView TypeName() noexcept { return "horus.pb.Zone"; }

  /// The full name of the message: `horus.pb.Zone`.
  StringView MessageTypeName() const noexcept final { return TypeName(); }

  // Field `zone_id` (no 1).
  // -----

  /// No documentation.
  ///
  /// Field no: 1.
  constexpr const CowBytes& zone_id() const& noexcept HORUS_LIFETIME_BOUND {
    return zone_id_;
  }

  /// If `zone_id` is set, moves it out of the message (without marking it as unset).
  ///
  /// Otherwise, returns a default-initialized value.
  ///
  /// Field no: 1.
  CowBytes zone_id() && noexcept {
    if (!set_fields_[0]) {
      return {};
    }
    return std::move(zone_id_);
  }

  /// No documentation.
  ///
  /// Field no: 1.
  CowBytes& mutable_zone_id() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[0] = true;
    return zone_id_;
  }

  /// Returns whether `zone_id` (no 1) is set.
  constexpr bool has_zone_id() const noexcept { return set_fields_[0]; }

  /// Clears `zone_id` (no 1).
  void clear_zone_id() & noexcept {
    set_fields_[0] = false;
    zone_id_ = {};
  }

  /// Sets `zone_id` (no 1) and returns `*this`.
  Zone& set_zone_id(CowBytes&& zone_id) & noexcept {
    set_fields_[0] = true;
    zone_id_ = std::move(zone_id);
    return *this;
  }
  /// Sets `zone_id` (no 1) and returns `*this`.
  Zone&& set_zone_id(CowBytes&& zone_id) && noexcept {
    return std::move(set_zone_id(std::move(zone_id)));
  }

  // Field `status` (no 2).
  // -----

  /// No documentation.
  ///
  /// Field no: 2.
  constexpr RepeatedMessageStatus status() const& noexcept HORUS_LIFETIME_BOUND {
    return status_;
  }

  /// No documentation.
  ///
  /// Field no: 2.
  RepeatedMessageStatus& mutable_status() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[1] = true;
    return status_;
  }

  /// Returns whether `status` (no 2) is set.
  constexpr bool has_status() const noexcept { return set_fields_[1]; }

  /// Clears `status` (no 2).
  void clear_status() & noexcept {
    set_fields_[1] = false;
    status_ = {};
  }

  /// Sets `status` (no 2) and returns `*this`.
  Zone& set_status(RepeatedMessageStatus status) & noexcept {
    set_fields_[1] = true;
    status_ = status;
    return *this;
  }
  /// Sets `status` (no 2) and returns `*this`.
  Zone&& set_status(RepeatedMessageStatus status) && noexcept {
    return std::move(set_status(status));
  }

  // Field `type` (no 3).
  // -----

  /// No documentation.
  ///
  /// Field no: 3.
  constexpr ZoneType type() const& noexcept HORUS_LIFETIME_BOUND {
    return type_;
  }

  /// No documentation.
  ///
  /// Field no: 3.
  ZoneType& mutable_type() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[2] = true;
    return type_;
  }

  /// Returns whether `type` (no 3) is set.
  constexpr bool has_type() const noexcept { return set_fields_[2]; }

  /// Clears `type` (no 3).
  void clear_type() & noexcept {
    set_fields_[2] = false;
    type_ = {};
  }

  /// Sets `type` (no 3) and returns `*this`.
  Zone& set_type(ZoneType type) & noexcept {
    set_fields_[2] = true;
    type_ = type;
    return *this;
  }
  /// Sets `type` (no 3) and returns `*this`.
  Zone&& set_type(ZoneType type) && noexcept {
    return std::move(set_type(type));
  }

  // Field `name` (no 4).
  // -----

  /// No documentation.
  ///
  /// Field no: 4.
  constexpr const CowBytes& name() const& noexcept HORUS_LIFETIME_BOUND {
    return name_;
  }

  /// If `name` is set, moves it out of the message (without marking it as unset).
  ///
  /// Otherwise, returns a default-initialized value.
  ///
  /// Field no: 4.
  CowBytes name() && noexcept {
    if (!set_fields_[3]) {
      return {};
    }
    return std::move(name_);
  }

  /// No documentation.
  ///
  /// Field no: 4.
  CowBytes& mutable_name() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[3] = true;
    return name_;
  }

  /// Returns whether `name` (no 4) is set.
  constexpr bool has_name() const noexcept { return set_fields_[3]; }

  /// Clears `name` (no 4).
  void clear_name() & noexcept {
    set_fields_[3] = false;
    name_ = {};
  }

  /// Sets `name` (no 4) and returns `*this`.
  Zone& set_name(CowBytes&& name) & noexcept {
    set_fields_[3] = true;
    name_ = std::move(name);
    return *this;
  }
  /// Sets `name` (no 4) and returns `*this`.
  Zone&& set_name(CowBytes&& name) && noexcept {
    return std::move(set_name(std::move(name)));
  }

  // Field `z_range` (no 5).
  // -----

  /// No documentation.
  ///
  /// Field no: 5.
  constexpr const Range& z_range() const& noexcept HORUS_LIFETIME_BOUND {
    return z_range_;
  }

  /// If `z_range` is set, moves it out of the message (without marking it as unset).
  ///
  /// Otherwise, returns a default-initialized value.
  ///
  /// Field no: 5.
  Range z_range() && noexcept {
    if (!set_fields_[4]) {
      return {};
    }
    return std::move(z_range_);
  }

  /// No documentation.
  ///
  /// Field no: 5.
  Range& mutable_z_range() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[4] = true;
    return z_range_;
  }

  /// Returns whether `z_range` (no 5) is set.
  constexpr bool has_z_range() const noexcept { return set_fields_[4]; }

  /// Clears `z_range` (no 5).
  void clear_z_range() & noexcept {
    set_fields_[4] = false;
    z_range_ = {};
  }

  /// Sets `z_range` (no 5) and returns `*this`.
  Zone& set_z_range(Range&& z_range) & noexcept {
    set_fields_[4] = true;
    z_range_ = std::move(z_range);
    return *this;
  }
  /// Sets `z_range` (no 5) and returns `*this`.
  Zone&& set_z_range(Range&& z_range) && noexcept {
    return std::move(set_z_range(std::move(z_range)));
  }

  // Field `vertices` (no 6).
  // -----

  /// No documentation.
  ///
  /// Field no: 6.
  constexpr const Vector2dList& vertices() const& noexcept HORUS_LIFETIME_BOUND {
    return vertices_;
  }

  /// If `vertices` is set, moves it out of the message (without marking it as unset).
  ///
  /// Otherwise, returns a default-initialized value.
  ///
  /// Field no: 6.
  Vector2dList vertices() && noexcept {
    if (!set_fields_[5]) {
      return {};
    }
    return std::move(vertices_);
  }

  /// No documentation.
  ///
  /// Field no: 6.
  Vector2dList& mutable_vertices() & noexcept HORUS_LIFETIME_BOUND {
    set_fields_[5] = true;
    return vertices_;
  }

  /// Returns whether `vertices` (no 6) is set.
  constexpr bool has_vertices() const noexcept { return set_fields_[5]; }

  /// Clears `vertices` (no 6).
  void clear_vertices() & noexcept {
    set_fields_[5] = false;
    vertices_ = {};
  }

  /// Sets `vertices` (no 6) and returns `*this`.
  Zone& set_vertices(Vector2dList&& vertices) & noexcept {
    set_fields_[5] = true;
    vertices_ = std::move(vertices);
    return *this;
  }
  /// Sets `vertices` (no 6) and returns `*this`.
  Zone&& set_vertices(Vector2dList&& vertices) && noexcept {
    return std::move(set_vertices(std::move(vertices)));
  }

 private:
  /// @see zone_id()
  CowBytes zone_id_{};
  /// @see status()
  RepeatedMessageStatus status_{};
  /// @see type()
  ZoneType type_{};
  /// @see name()
  CowBytes name_{};
  /// @see z_range()
  Range z_range_{};
  /// @see vertices()
  Vector2dList vertices_{};

  /// The set of fields that have been given an explicit value.
  std::bitset<6> set_fields_;
};

}  // namespace pb
}  // namespace sdk
}  // namespace horus

// MARK: Enum traits

namespace horus {

template <>
class PbEnumTraits<horus::sdk::pb::ZoneType> final {
 public:
  /// The full name of the enum: `horus.sdk.pb.ZoneType`.
  static constexpr StringView EnumName() noexcept { return "horus.sdk.pb.ZoneType"; }

  /// Returns the name of the given enumerator, or an empty string.
  static constexpr StringView NameOf(horus::sdk::pb::ZoneType value) noexcept {
    switch (value) {
      case horus::sdk::pb::ZoneType::kUnspecified: {
        return "ZONE_TYPE_UNSPECIFIED";
      }
      case horus::sdk::pb::ZoneType::kExclusion: {
        return "EXCLUSION";
      }
      case horus::sdk::pb::ZoneType::kStaticDetection: {
        return "STATIC_DETECTION";
      }
      case horus::sdk::pb::ZoneType::kReflection: {
        return "REFLECTION";
      }
      case horus::sdk::pb::ZoneType::kStaticExclusion: {
        return "STATIC_EXCLUSION";
      }
      case horus::sdk::pb::ZoneType::kEvent: {
        return "EVENT";
      }
      case horus::sdk::pb::ZoneType::kUnknownWireValue:
      default: {
        return "";
      }
    }
  }

  /// Returns the value corresponding to the given name, or `default_value`.
  static constexpr horus::sdk::pb::ZoneType ValueOf(PbEnum value, horus::sdk::pb::ZoneType default_value = horus::sdk::pb::ZoneType::kUnknownWireValue) noexcept {
    switch (value) {
      case 0: {
        return horus::sdk::pb::ZoneType::kUnspecified;
      }
      case 1: {
        return horus::sdk::pb::ZoneType::kExclusion;
      }
      case 2: {
        return horus::sdk::pb::ZoneType::kStaticDetection;
      }
      case 3: {
        return horus::sdk::pb::ZoneType::kReflection;
      }
      case 4: {
        return horus::sdk::pb::ZoneType::kStaticExclusion;
      }
      case 5: {
        return horus::sdk::pb::ZoneType::kEvent;
      }
      default: {
        return default_value;
      }
    }
  }

  /// Returns the value corresponding to the given name, or `default_value`.
  static constexpr horus::sdk::pb::ZoneType ValueOf(StringView name, horus::sdk::pb::ZoneType default_value = horus::sdk::pb::ZoneType::kUnknownWireValue) noexcept {
    if (name == "ZONE_TYPE_UNSPECIFIED") {
      return horus::sdk::pb::ZoneType::kUnspecified;
    }
    if (name == "EXCLUSION") {
      return horus::sdk::pb::ZoneType::kExclusion;
    }
    if (name == "STATIC_DETECTION") {
      return horus::sdk::pb::ZoneType::kStaticDetection;
    }
    if (name == "REFLECTION") {
      return horus::sdk::pb::ZoneType::kReflection;
    }
    if (name == "STATIC_EXCLUSION") {
      return horus::sdk::pb::ZoneType::kStaticExclusion;
    }
    if (name == "EVENT") {
      return horus::sdk::pb::ZoneType::kEvent;
    }
    return default_value;
  }
};

template <>
class PbTraits<horus::sdk::pb::ZoneType> final {
 public:
  /// Serializes `value` into `writer`.
  static void Serialize(PbWriter& writer, PbTag tag, horus::sdk::pb::ZoneType value) {
    writer.Writer().add_enum(tag, static_cast<PbEnum>(value));
  }

  /// Deserializes `horus::sdk::pb::ZoneType` from `reader`.
  static horus::sdk::pb::ZoneType Deserialize(PbReader& reader) {
    return PbEnumTraits<horus::sdk::pb::ZoneType>::ValueOf(reader.Reader().get_enum());
  }
};

}  // namespace horus

namespace horus {
namespace sdk {
namespace pb {

/// Appends `value` to `sink`.
template <class Sink>
void HorusStringify(Sink& sink, ZoneType value) noexcept(noexcept(sink.Append(StringView{}))) {
  sink.Append(PbEnumTraits<ZoneType>::NameOf(value));
}

}  // namespace pb
}  // namespace sdk
}  // namespace horus

// NOLINTEND(readability-identifier-length)

#endif  // HORUS_PB_CONFIG_SCHEMA_ZONE_PB_H_
