// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.28.3
// source: horus/pb/rpc.proto

package rpc_pb

import (
	logs_pb "github.com/seoulrobotics/horus-sdk/go/proto/logs/logs_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Indicates that no response is expected, and that the client does not need to
// wait for a response.
type NoResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoResponse) Reset() {
	*x = NoResponse{}
	mi := &file_horus_pb_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoResponse) ProtoMessage() {}

func (x *NoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type NoResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 NoResponse_builder) Build() *NoResponse {
	m0 := &NoResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Protobuf metadata options specified on RPC services and methods.
type RpcServiceOptions struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	xxx_hidden_Description string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RpcServiceOptions) Reset() {
	*x = RpcServiceOptions{}
	mi := &file_horus_pb_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcServiceOptions) ProtoMessage() {}

func (x *RpcServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RpcServiceOptions) GetId() uint32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *RpcServiceOptions) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *RpcServiceOptions) SetId(v uint32) {
	x.xxx_hidden_Id = v
}

func (x *RpcServiceOptions) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

type RpcServiceOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The identifier of the service.
	//
	// Must be unique across all services.
	//
	// Cannot be 0.
	//
	// To determine available service IDs for a new service, run
	//
	//	horus cat service_ids.txt
	Id uint32
	// The description of the service shown in the generated code.
	Description string
}

func (b0 RpcServiceOptions_builder) Build() *RpcServiceOptions {
	m0 := &RpcServiceOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Description = b.Description
	return m0
}

// Protobuf method options for in house-RPC.
type RpcMethodOptions struct {
	state                  protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Id          uint32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	xxx_hidden_Description string                  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	xxx_hidden_Type        isRpcMethodOptions_Type `protobuf_oneof:"type"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RpcMethodOptions) Reset() {
	*x = RpcMethodOptions{}
	mi := &file_horus_pb_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcMethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcMethodOptions) ProtoMessage() {}

func (x *RpcMethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RpcMethodOptions) GetId() uint32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *RpcMethodOptions) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *RpcMethodOptions) GetSubscribe() *RpcMethodOptions_SubscribeMethod {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*rpcMethodOptions_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *RpcMethodOptions) GetUnsubscribe() *RpcMethodOptions_UnsubscribeMethod {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*rpcMethodOptions_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *RpcMethodOptions) SetId(v uint32) {
	x.xxx_hidden_Id = v
}

func (x *RpcMethodOptions) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *RpcMethodOptions) SetSubscribe(v *RpcMethodOptions_SubscribeMethod) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &rpcMethodOptions_Subscribe{v}
}

func (x *RpcMethodOptions) SetUnsubscribe(v *RpcMethodOptions_UnsubscribeMethod) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &rpcMethodOptions_Unsubscribe{v}
}

func (x *RpcMethodOptions) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *RpcMethodOptions) HasSubscribe() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*rpcMethodOptions_Subscribe)
	return ok
}

func (x *RpcMethodOptions) HasUnsubscribe() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*rpcMethodOptions_Unsubscribe)
	return ok
}

func (x *RpcMethodOptions) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *RpcMethodOptions) ClearSubscribe() {
	if _, ok := x.xxx_hidden_Type.(*rpcMethodOptions_Subscribe); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *RpcMethodOptions) ClearUnsubscribe() {
	if _, ok := x.xxx_hidden_Type.(*rpcMethodOptions_Unsubscribe); ok {
		x.xxx_hidden_Type = nil
	}
}

const RpcMethodOptions_Type_not_set_case case_RpcMethodOptions_Type = 0
const RpcMethodOptions_Subscribe_case case_RpcMethodOptions_Type = 3
const RpcMethodOptions_Unsubscribe_case case_RpcMethodOptions_Type = 4

func (x *RpcMethodOptions) WhichType() case_RpcMethodOptions_Type {
	if x == nil {
		return RpcMethodOptions_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *rpcMethodOptions_Subscribe:
		return RpcMethodOptions_Subscribe_case
	case *rpcMethodOptions_Unsubscribe:
		return RpcMethodOptions_Unsubscribe_case
	default:
		return RpcMethodOptions_Type_not_set_case
	}
}

type RpcMethodOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The identifier of the method.
	//
	// Must be unique across methods within a service.
	//
	// Cannot be 0.
	Id uint32
	// The description of the service or method shown in the generated code.
	Description string
	// The type of the method. This is optional, but may affect generated code.

	// Fields of oneof xxx_hidden_Type:
	// The method is meant to set up a subscription, and will have a default
	// implementation in C++.
	Subscribe *RpcMethodOptions_SubscribeMethod
	// The method is meant to tear down a subscription, and will have a default
	// implementation in C++.
	Unsubscribe *RpcMethodOptions_UnsubscribeMethod
	// -- end of xxx_hidden_Type
}

func (b0 RpcMethodOptions_builder) Build() *RpcMethodOptions {
	m0 := &RpcMethodOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Description = b.Description
	if b.Subscribe != nil {
		x.xxx_hidden_Type = &rpcMethodOptions_Subscribe{b.Subscribe}
	}
	if b.Unsubscribe != nil {
		x.xxx_hidden_Type = &rpcMethodOptions_Unsubscribe{b.Unsubscribe}
	}
	return m0
}

type case_RpcMethodOptions_Type protoreflect.FieldNumber

func (x case_RpcMethodOptions_Type) String() string {
	md := file_horus_pb_rpc_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isRpcMethodOptions_Type interface {
	isRpcMethodOptions_Type()
}

type rpcMethodOptions_Subscribe struct {
	// The method is meant to set up a subscription, and will have a default
	// implementation in C++.
	Subscribe *RpcMethodOptions_SubscribeMethod `protobuf:"bytes,3,opt,name=subscribe,proto3,oneof"`
}

type rpcMethodOptions_Unsubscribe struct {
	// The method is meant to tear down a subscription, and will have a default
	// implementation in C++.
	Unsubscribe *RpcMethodOptions_UnsubscribeMethod `protobuf:"bytes,4,opt,name=unsubscribe,proto3,oneof"`
}

func (*rpcMethodOptions_Subscribe) isRpcMethodOptions_Type() {}

func (*rpcMethodOptions_Unsubscribe) isRpcMethodOptions_Type() {}

type DefaultSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultSubscribeRequest) Reset() {
	*x = DefaultSubscribeRequest{}
	mi := &file_horus_pb_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultSubscribeRequest) ProtoMessage() {}

func (x *DefaultSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DefaultSubscribeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DefaultSubscribeRequest_builder) Build() *DefaultSubscribeRequest {
	m0 := &DefaultSubscribeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DefaultSubscribeResponse struct {
	state            protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Error isDefaultSubscribeResponse_Error `protobuf_oneof:"error"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DefaultSubscribeResponse) Reset() {
	*x = DefaultSubscribeResponse{}
	mi := &file_horus_pb_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultSubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultSubscribeResponse) ProtoMessage() {}

func (x *DefaultSubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DefaultSubscribeResponse) GetConnectionError() *logs_pb.RpcConnectionError {
	if x != nil {
		if x, ok := x.xxx_hidden_Error.(*defaultSubscribeResponse_ConnectionError); ok {
			return x.ConnectionError
		}
	}
	return nil
}

func (x *DefaultSubscribeResponse) SetConnectionError(v *logs_pb.RpcConnectionError) {
	if v == nil {
		x.xxx_hidden_Error = nil
		return
	}
	x.xxx_hidden_Error = &defaultSubscribeResponse_ConnectionError{v}
}

func (x *DefaultSubscribeResponse) HasError() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Error != nil
}

func (x *DefaultSubscribeResponse) HasConnectionError() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Error.(*defaultSubscribeResponse_ConnectionError)
	return ok
}

func (x *DefaultSubscribeResponse) ClearError() {
	x.xxx_hidden_Error = nil
}

func (x *DefaultSubscribeResponse) ClearConnectionError() {
	if _, ok := x.xxx_hidden_Error.(*defaultSubscribeResponse_ConnectionError); ok {
		x.xxx_hidden_Error = nil
	}
}

const DefaultSubscribeResponse_Error_not_set_case case_DefaultSubscribeResponse_Error = 0
const DefaultSubscribeResponse_ConnectionError_case case_DefaultSubscribeResponse_Error = 1

func (x *DefaultSubscribeResponse) WhichError() case_DefaultSubscribeResponse_Error {
	if x == nil {
		return DefaultSubscribeResponse_Error_not_set_case
	}
	switch x.xxx_hidden_Error.(type) {
	case *defaultSubscribeResponse_ConnectionError:
		return DefaultSubscribeResponse_ConnectionError_case
	default:
		return DefaultSubscribeResponse_Error_not_set_case
	}
}

type DefaultSubscribeResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Error:
	ConnectionError *logs_pb.RpcConnectionError
	// -- end of xxx_hidden_Error
}

func (b0 DefaultSubscribeResponse_builder) Build() *DefaultSubscribeResponse {
	m0 := &DefaultSubscribeResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ConnectionError != nil {
		x.xxx_hidden_Error = &defaultSubscribeResponse_ConnectionError{b.ConnectionError}
	}
	return m0
}

type case_DefaultSubscribeResponse_Error protoreflect.FieldNumber

func (x case_DefaultSubscribeResponse_Error) String() string {
	md := file_horus_pb_rpc_proto_msgTypes[4].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isDefaultSubscribeResponse_Error interface {
	isDefaultSubscribeResponse_Error()
}

type defaultSubscribeResponse_ConnectionError struct {
	ConnectionError *logs_pb.RpcConnectionError `protobuf:"bytes,1,opt,name=connection_error,json=connectionError,proto3,oneof"`
}

func (*defaultSubscribeResponse_ConnectionError) isDefaultSubscribeResponse_Error() {}

type DefaultUnsubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DefaultUnsubscribeRequest) Reset() {
	*x = DefaultUnsubscribeRequest{}
	mi := &file_horus_pb_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultUnsubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultUnsubscribeRequest) ProtoMessage() {}

func (x *DefaultUnsubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DefaultUnsubscribeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DefaultUnsubscribeRequest_builder) Build() *DefaultUnsubscribeRequest {
	m0 := &DefaultUnsubscribeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DefaultUnsubscribeResponse struct {
	state            protoimpl.MessageState             `protogen:"opaque.v1"`
	xxx_hidden_Error isDefaultUnsubscribeResponse_Error `protobuf_oneof:"error"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DefaultUnsubscribeResponse) Reset() {
	*x = DefaultUnsubscribeResponse{}
	mi := &file_horus_pb_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DefaultUnsubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultUnsubscribeResponse) ProtoMessage() {}

func (x *DefaultUnsubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DefaultUnsubscribeResponse) GetDisconnectionError() *logs_pb.RpcDisconnectionError {
	if x != nil {
		if x, ok := x.xxx_hidden_Error.(*defaultUnsubscribeResponse_DisconnectionError); ok {
			return x.DisconnectionError
		}
	}
	return nil
}

func (x *DefaultUnsubscribeResponse) SetDisconnectionError(v *logs_pb.RpcDisconnectionError) {
	if v == nil {
		x.xxx_hidden_Error = nil
		return
	}
	x.xxx_hidden_Error = &defaultUnsubscribeResponse_DisconnectionError{v}
}

func (x *DefaultUnsubscribeResponse) HasError() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Error != nil
}

func (x *DefaultUnsubscribeResponse) HasDisconnectionError() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Error.(*defaultUnsubscribeResponse_DisconnectionError)
	return ok
}

func (x *DefaultUnsubscribeResponse) ClearError() {
	x.xxx_hidden_Error = nil
}

func (x *DefaultUnsubscribeResponse) ClearDisconnectionError() {
	if _, ok := x.xxx_hidden_Error.(*defaultUnsubscribeResponse_DisconnectionError); ok {
		x.xxx_hidden_Error = nil
	}
}

const DefaultUnsubscribeResponse_Error_not_set_case case_DefaultUnsubscribeResponse_Error = 0
const DefaultUnsubscribeResponse_DisconnectionError_case case_DefaultUnsubscribeResponse_Error = 1

func (x *DefaultUnsubscribeResponse) WhichError() case_DefaultUnsubscribeResponse_Error {
	if x == nil {
		return DefaultUnsubscribeResponse_Error_not_set_case
	}
	switch x.xxx_hidden_Error.(type) {
	case *defaultUnsubscribeResponse_DisconnectionError:
		return DefaultUnsubscribeResponse_DisconnectionError_case
	default:
		return DefaultUnsubscribeResponse_Error_not_set_case
	}
}

type DefaultUnsubscribeResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Error:
	DisconnectionError *logs_pb.RpcDisconnectionError
	// -- end of xxx_hidden_Error
}

func (b0 DefaultUnsubscribeResponse_builder) Build() *DefaultUnsubscribeResponse {
	m0 := &DefaultUnsubscribeResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DisconnectionError != nil {
		x.xxx_hidden_Error = &defaultUnsubscribeResponse_DisconnectionError{b.DisconnectionError}
	}
	return m0
}

type case_DefaultUnsubscribeResponse_Error protoreflect.FieldNumber

func (x case_DefaultUnsubscribeResponse_Error) String() string {
	md := file_horus_pb_rpc_proto_msgTypes[6].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isDefaultUnsubscribeResponse_Error interface {
	isDefaultUnsubscribeResponse_Error()
}

type defaultUnsubscribeResponse_DisconnectionError struct {
	DisconnectionError *logs_pb.RpcDisconnectionError `protobuf:"bytes,1,opt,name=disconnection_error,json=disconnectionError,proto3,oneof"`
}

func (*defaultUnsubscribeResponse_DisconnectionError) isDefaultUnsubscribeResponse_Error() {}

type RpcMethodOptions_SubscribeMethod struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SubscriberName string                 `protobuf:"bytes,1,opt,name=subscriber_name,json=subscriberName,proto3" json:"subscriber_name,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RpcMethodOptions_SubscribeMethod) Reset() {
	*x = RpcMethodOptions_SubscribeMethod{}
	mi := &file_horus_pb_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcMethodOptions_SubscribeMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcMethodOptions_SubscribeMethod) ProtoMessage() {}

func (x *RpcMethodOptions_SubscribeMethod) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RpcMethodOptions_SubscribeMethod) GetSubscriberName() string {
	if x != nil {
		return x.xxx_hidden_SubscriberName
	}
	return ""
}

func (x *RpcMethodOptions_SubscribeMethod) SetSubscriberName(v string) {
	x.xxx_hidden_SubscriberName = v
}

type RpcMethodOptions_SubscribeMethod_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The type name of the subscriber.
	SubscriberName string
}

func (b0 RpcMethodOptions_SubscribeMethod_builder) Build() *RpcMethodOptions_SubscribeMethod {
	m0 := &RpcMethodOptions_SubscribeMethod{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SubscriberName = b.SubscriberName
	return m0
}

type RpcMethodOptions_UnsubscribeMethod struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SubscriberName string                 `protobuf:"bytes,1,opt,name=subscriber_name,json=subscriberName,proto3" json:"subscriber_name,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RpcMethodOptions_UnsubscribeMethod) Reset() {
	*x = RpcMethodOptions_UnsubscribeMethod{}
	mi := &file_horus_pb_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcMethodOptions_UnsubscribeMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcMethodOptions_UnsubscribeMethod) ProtoMessage() {}

func (x *RpcMethodOptions_UnsubscribeMethod) ProtoReflect() protoreflect.Message {
	mi := &file_horus_pb_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RpcMethodOptions_UnsubscribeMethod) GetSubscriberName() string {
	if x != nil {
		return x.xxx_hidden_SubscriberName
	}
	return ""
}

func (x *RpcMethodOptions_UnsubscribeMethod) SetSubscriberName(v string) {
	x.xxx_hidden_SubscriberName = v
}

type RpcMethodOptions_UnsubscribeMethod_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The type name of the subscriber.
	SubscriberName string
}

func (b0 RpcMethodOptions_UnsubscribeMethod_builder) Build() *RpcMethodOptions_UnsubscribeMethod {
	m0 := &RpcMethodOptions_UnsubscribeMethod{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SubscriberName = b.SubscriberName
	return m0
}

var file_horus_pb_rpc_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*RpcServiceOptions)(nil),
		Field:         12159672,
		Name:          "horus.pb.service_options",
		Tag:           "bytes,12159672,opt,name=service_options",
		Filename:      "horus/pb/rpc.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*RpcMethodOptions)(nil),
		Field:         12159672,
		Name:          "horus.pb.method_options",
		Tag:           "bytes,12159672,opt,name=method_options",
		Filename:      "horus/pb/rpc.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional horus.pb.RpcServiceOptions service_options = 12159672;
	E_ServiceOptions = &file_horus_pb_rpc_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional horus.pb.RpcMethodOptions method_options = 12159672;
	E_MethodOptions = &file_horus_pb_rpc_proto_extTypes[1]
)

var File_horus_pb_rpc_proto protoreflect.FileDescriptor

var file_horus_pb_rpc_proto_rawDesc = []byte{
	0x0a, 0x12, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x1a, 0x20,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x18, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x6c, 0x6f, 0x67, 0x73, 0x2f,
	0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0c, 0x0a, 0x0a, 0x4e, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x45, 0x0a, 0x11, 0x52, 0x70, 0x63, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0xe4, 0x02, 0x0a, 0x10, 0x52, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x4a, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x68, 0x6f, 0x72, 0x75,
	0x73, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x48, 0x00, 0x52, 0x09, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x12, 0x50, 0x0a, 0x0b, 0x75, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e,
	0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x75, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x1a, 0x3a, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x1a, 0x3c, 0x0a, 0x11, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x06,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x73, 0x0a, 0x18, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a,
	0x10, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e,
	0x70, 0x62, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x52, 0x70, 0x63, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0f, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x07, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x1b, 0x0a, 0x19, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x7e, 0x0a, 0x1a, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x55, 0x6e,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x57, 0x0a, 0x13, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x6c, 0x6f, 0x67, 0x73, 0x2e, 0x52,
	0x70, 0x63, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x12, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x3a, 0x6b, 0x0a, 0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb8, 0x95, 0xe6, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x88, 0x01, 0x01,
	0x3a, 0x67, 0x0a, 0x0e, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0xb8, 0x95, 0xe6, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x6f,
	0x72, 0x75, 0x73, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0d, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x88, 0x01, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var file_horus_pb_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_horus_pb_rpc_proto_goTypes = []any{
	(*NoResponse)(nil),                         // 0: horus.pb.NoResponse
	(*RpcServiceOptions)(nil),                  // 1: horus.pb.RpcServiceOptions
	(*RpcMethodOptions)(nil),                   // 2: horus.pb.RpcMethodOptions
	(*DefaultSubscribeRequest)(nil),            // 3: horus.pb.DefaultSubscribeRequest
	(*DefaultSubscribeResponse)(nil),           // 4: horus.pb.DefaultSubscribeResponse
	(*DefaultUnsubscribeRequest)(nil),          // 5: horus.pb.DefaultUnsubscribeRequest
	(*DefaultUnsubscribeResponse)(nil),         // 6: horus.pb.DefaultUnsubscribeResponse
	(*RpcMethodOptions_SubscribeMethod)(nil),   // 7: horus.pb.RpcMethodOptions.SubscribeMethod
	(*RpcMethodOptions_UnsubscribeMethod)(nil), // 8: horus.pb.RpcMethodOptions.UnsubscribeMethod
	(*logs_pb.RpcConnectionError)(nil),         // 9: horus.pb.logs.RpcConnectionError
	(*logs_pb.RpcDisconnectionError)(nil),      // 10: horus.pb.logs.RpcDisconnectionError
	(*descriptorpb.ServiceOptions)(nil),        // 11: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),         // 12: google.protobuf.MethodOptions
}
var file_horus_pb_rpc_proto_depIdxs = []int32{
	7,  // 0: horus.pb.RpcMethodOptions.subscribe:type_name -> horus.pb.RpcMethodOptions.SubscribeMethod
	8,  // 1: horus.pb.RpcMethodOptions.unsubscribe:type_name -> horus.pb.RpcMethodOptions.UnsubscribeMethod
	9,  // 2: horus.pb.DefaultSubscribeResponse.connection_error:type_name -> horus.pb.logs.RpcConnectionError
	10, // 3: horus.pb.DefaultUnsubscribeResponse.disconnection_error:type_name -> horus.pb.logs.RpcDisconnectionError
	11, // 4: horus.pb.service_options:extendee -> google.protobuf.ServiceOptions
	12, // 5: horus.pb.method_options:extendee -> google.protobuf.MethodOptions
	1,  // 6: horus.pb.service_options:type_name -> horus.pb.RpcServiceOptions
	2,  // 7: horus.pb.method_options:type_name -> horus.pb.RpcMethodOptions
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	6,  // [6:8] is the sub-list for extension type_name
	4,  // [4:6] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_horus_pb_rpc_proto_init() }
func file_horus_pb_rpc_proto_init() {
	if File_horus_pb_rpc_proto != nil {
		return
	}
	file_horus_pb_rpc_proto_msgTypes[2].OneofWrappers = []any{
		(*rpcMethodOptions_Subscribe)(nil),
		(*rpcMethodOptions_Unsubscribe)(nil),
	}
	file_horus_pb_rpc_proto_msgTypes[4].OneofWrappers = []any{
		(*defaultSubscribeResponse_ConnectionError)(nil),
	}
	file_horus_pb_rpc_proto_msgTypes[6].OneofWrappers = []any{
		(*defaultUnsubscribeResponse_DisconnectionError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_horus_pb_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_horus_pb_rpc_proto_goTypes,
		DependencyIndexes: file_horus_pb_rpc_proto_depIdxs,
		MessageInfos:      file_horus_pb_rpc_proto_msgTypes,
		ExtensionInfos:    file_horus_pb_rpc_proto_extTypes,
	}.Build()
	File_horus_pb_rpc_proto = out.File
	file_horus_pb_rpc_proto_rawDesc = nil
	file_horus_pb_rpc_proto_goTypes = nil
	file_horus_pb_rpc_proto_depIdxs = nil
}
